/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type FooMember3Grault, FooMember3GraultFromJSON, FooMember3GraultFromJSONTyped, FooMember3GraultToJSON, instanceOfFooMember3Grault } from './FooMember3Grault';

/** Third inline object type */
export interface FooMember3 {
  grault: FooMember3Grault,
}

export function instanceOfFooMember3(value: unknown): value is FooMember3 {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "grault" in value && (value as any)["grault"] !== undefined;
  const hasAllTsNames =
    "grault" in value && (value as any)["grault"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function FooMember3FromJSON(json: any): FooMember3 {
  return FooMember3FromJSONTyped(json, false);
}

export function FooMember3FromJSONTyped(json: any, ignoreDiscriminator: boolean): FooMember3 {
  if (json == null) {
    return json;
  }
  return {
    'grault': FooMember3GraultFromJSON(json['grault']),
  };
}

export function FooMember3ToJSON(value?: FooMember3 | null): any {
  return FooMember3ToJSONTyped(value, false);
}

export function FooMember3ToJSONTyped(value?: FooMember3 | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'grault': FooMember3GraultToJSON(value['grault']),
  };
}

export const FooMember3PropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};