/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
export * from './Foo';
export * from './FooBar';
export * from './FooGrault';
export * from './FooMember1';
export * from './FooMember1Bar';
export * from './FooMember2';
export * from './FooMember2Quux';
export * from './FooMember3';
export * from './FooMember3Grault';
export * from './FooQuux';
