//! Go HTTP code generator: IR + sigil-stitch, one cut-over from minijinja.
//!
//! Orchestrates the end-to-end pipeline:
//! 1. Lower the `OpenApiV31Spec` to an `IrSpec` via `openapi-nexus-ir`.
//! 2. Emit models via `sigil_emit::generate_model_files`.
//! 3. Emit APIs via `sigil_emit_api::generate_api_files`.
//! 4. Stamp the hardcoded runtime (`client.go`, `auth.go`, `errors.go`).
//! 5. Emit `go.mod` and `README.md`.

use std::error::Error;

use heck::ToKebabCase as _;

use crate::config::GoHttpConfig;
use crate::runtime::runtime_files;
use crate::{sigil_emit, sigil_emit_api};
use openapi_nexus_common::{GeneratorType, Language};
use openapi_nexus_core::traits::code_generator::CodeGenerator;
use openapi_nexus_core::traits::file_writer::{FileInfo, FileWriter};
use openapi_nexus_ir::types::{IrInfo, IrSpec};
use openapi_nexus_spec::OpenApiV31Spec;

const DEFAULT_MODULE_PATH: &str = "example.com/sdk";

/// Go HTTP code generator.
#[derive(Debug, Clone)]
pub struct GoHttpCodeGenerator {
    config: GoHttpConfig,
}

impl GoHttpCodeGenerator {
    /// Create a new Go HTTP generator from a TOML config fragment.
    pub fn new(config: toml::value::Table) -> Self {
        Self {
            config: GoHttpConfig::from(config),
        }
    }

    fn module_path(&self) -> String {
        self.config
            .module_path
            .clone()
            .unwrap_or_else(|| DEFAULT_MODULE_PATH.to_string())
    }

    /// Orchestrate emission from the lowered IR.
    fn generate_from_ir(&self, ir: &IrSpec) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        let module_path = self.module_path();
        let header = render_file_header(&ir.info);

        let mut files = Vec::new();

        // Models
        files.extend(
            sigil_emit::generate_model_files(ir, &header).map_err(|msg| {
                Box::<dyn Error + Send + Sync>::from(format!("sigil_emit models: {msg}"))
            })?,
        );

        // APIs
        files.extend(
            sigil_emit_api::generate_api_files(ir, &module_path, &header).map_err(|msg| {
                Box::<dyn Error + Send + Sync>::from(format!("sigil_emit_api: {msg}"))
            })?,
        );

        // Runtime (hardcoded)
        files.extend(runtime_files(&header));

        // Project files: go.mod, README.md
        files.push(go_mod_file(&module_path));
        files.push(readme_file(&ir.info));

        Ok(files)
    }
}

impl CodeGenerator for GoHttpCodeGenerator {
    fn language(&self) -> Language {
        Language::Go
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::GoHttp
    }

    fn generate(
        &self,
        openapi: &OpenApiV31Spec,
    ) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        let ir = openapi_nexus_ir::lower::v31::lower_v31(openapi)?;
        tracing::info!(
            "Go generator using IR pipeline ({} schemas, {} operations)",
            ir.schemas.len(),
            ir.operations.len()
        );
        self.generate_from_ir(&ir)
    }
}

impl FileWriter for GoHttpCodeGenerator {}

fn render_file_header(info: &IrInfo) -> String {
    let mut out = String::new();
    out.push_str("// Code generated by openapi-nexus. DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str(&format!("// {} — {}\n", info.title, info.version));
    if let Some(desc) = &info.description {
        for line in desc.lines() {
            out.push_str(&format!("// {line}\n"));
        }
    }
    out.push('\n');
    out
}

fn go_mod_file(module_path: &str) -> FileInfo {
    let content = format!("module {module_path}\n\ngo 1.21\n");
    FileInfo::project("go.mod".to_string(), content)
}

fn readme_file(info: &IrInfo) -> FileInfo {
    let title = &info.title;
    let version = &info.version;
    let description = info
        .description
        .clone()
        .unwrap_or_else(|| "Generated Go SDK.".to_string());
    let package = info.title.to_kebab_case();
    let content = format!(
        "# {title}\n\n{description}\n\nVersion: `{version}`\n\nGenerated by [openapi-nexus](https://github.com/adamcavendish/openapi-nexus) for `{package}`.\n"
    );
    FileInfo::readme("README.md".to_string(), content)
}
