// Code generated by openapi-nexus. DO NOT EDIT.
// Array of Referenced Types Test
//
// Test case for array of referenced model types with recursive FromJSON calls
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

// Response containing array of User references
type ResponseListUsers struct {
	Users []User `json:"users"`
}

func (c ResponseListUsers) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ResponseListUsers) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"users",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *ResponseListUsers) GetUsers() []User {
	if c == nil {
		var zero []User
		return zero
	}
	return c.Users
}

