// Code generated by openapi-nexus. DO NOT EDIT.
// Naming Conventions Test
//
// Test fixture to verify language property naming conventions
//
// Generated from OpenAPI doc version 1.0.0

package operations

import (
	"example.com/sdk/internal/config"
	"example.com/sdk/internal/hooks"
	"example.com/sdk/internal/utils"
	"example.com/sdk/models/components"
	"example.com/sdk/models/operations"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

// Default - default operations
type Default struct {
	rootSDK          *NamingConventionsTestSDK
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newDefault(rootSDK *NamingConventionsTestSDK, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Default {
	return &Default{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
	}
}

// GetWithQueryParams - GET /test
func (s *Default) GetWithQueryParams(
	ctx context.Context,
	querySnakeCaseParam string,
	querySnakeCaseNumber string,
	queryKebabCaseParam string,
	queryKebabCaseArray []string,
	queryPascalCaseParam string,
	queryPascalCaseNumber string,
	queryScreamingSnakeCase string,
	queryScreamingNumber string,
	queryCamelCaseParam string,
	queryCamelCaseNumber string,
	querySingleword string,
	queryId string,
	opts ...operations.Option,
) (*operations.GetWithQueryParamsResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/test")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "get_with_query_params",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}

	// Build query parameters
	queryParams := struct {
		SnakeCaseParam string `queryParam:"name=snake_case_param,style=form,explode=true"`
		SnakeCaseNumber string `queryParam:"name=snake_case_number,style=form,explode=true"`
		KebabCaseParam string `queryParam:"name=kebab-case-param,style=form,explode=true"`
		KebabCaseArray []string `queryParam:"name=kebab-case-array,style=form,explode=true"`
		PascalCaseParam string `queryParam:"name=PascalCaseParam,style=form,explode=true"`
		PascalCaseNumber string `queryParam:"name=PascalCaseNumber,style=form,explode=true"`
		ScreamingSnakeCase string `queryParam:"name=SCREAMING_SNAKE_CASE,style=form,explode=true"`
		ScreamingNumber string `queryParam:"name=SCREAMING_NUMBER,style=form,explode=true"`
		CamelCaseParam string `queryParam:"name=camelCaseParam,style=form,explode=true"`
		CamelCaseNumber string `queryParam:"name=camelCaseNumber,style=form,explode=true"`
		Singleword string `queryParam:"name=singleword,style=form,explode=true"`
		Id string `queryParam:"name=id,style=form,explode=true"`
	}{
		SnakeCaseParam: querySnakeCaseParam,
		SnakeCaseNumber: querySnakeCaseNumber,
		KebabCaseParam: queryKebabCaseParam,
		KebabCaseArray: queryKebabCaseArray,
		PascalCaseParam: queryPascalCaseParam,
		PascalCaseNumber: queryPascalCaseNumber,
		ScreamingSnakeCase: queryScreamingSnakeCase,
		ScreamingNumber: queryScreamingNumber,
		CamelCaseParam: queryCamelCaseParam,
		CamelCaseNumber: queryCamelCaseNumber,
		Singleword: querySingleword,
		Id: queryId,
	}
	if err := utils.PopulateQueryParams(ctx, req, queryParams, nil); err != nil {
		return nil, err
	}


	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.GetWithQueryParamsResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// TestNamingConventions - POST /test
func (s *Default) TestNamingConventions(
	ctx context.Context,
	request components.TestNamingConventionsRequest,
	opts ...operations.Option,
) (*operations.TestNamingConventionsResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/test")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "test_naming_conventions",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	bodyReader, reqContentType, err := utils.SerializeRequestBody(ctx, request, false, false, "Request", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "POST", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.TestNamingConventionsResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

