// Code generated by openapi-nexus. DO NOT EDIT.
// Naming Conventions Test
//
// Test fixture to verify language property naming conventions
//
// Generated from OpenAPI doc version 1.0.0

package sdk

// TODO: Implement main SDK file
