/* tslint:disable */
/* eslint-disable */
/**
 * Array of Inline Objects Test
 *
 * Test case for array of inline objects with snake_case to camelCase conversion (main case from user issue)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
/**
 * Response containing a list of inference services - main test case for recursive JSON parsing
 */
export interface ResponseListInfrSvcs {
  inferenceServices: Array<{ createdAt: string; numReadyReplicas: number; numTotalReplicas: number; status: "decommissioned" | "degraded" | "running"; uid: string }>,
}

export function instanceOfResponseListInfrSvcs(value: object): value is ResponseListInfrSvcs {
  if (!('inferenceServices' in value) || (value as any)['inferenceServices'] === undefined) return false;
  return true;
}

export function ResponseListInfrSvcsFromJSON(json: any): ResponseListInfrSvcs {
  return ResponseListInfrSvcsFromJSONTyped(json, false);
}

export function ResponseListInfrSvcsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListInfrSvcs {
  if (json == null) {
    return json;
  }
  return {
    'inferenceServices': json['inference_services'].map((item: any) => ({
      createdAt: item['created_at'],
      numReadyReplicas: item['num_ready_replicas'],
      numTotalReplicas: item['num_total_replicas'],
      status: item['status'],
      uid: item['uid'],
    })),
  };
}

export function ResponseListInfrSvcsToJSON(value?: ResponseListInfrSvcs | null): any {
  return ResponseListInfrSvcsToJSONTyped(value, false);
}

export function ResponseListInfrSvcsToJSONTyped(value?: ResponseListInfrSvcs | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'inference_services': value['inferenceServices']?.map((item: any) => ({
      'created_at': item['createdAt'],
      'num_ready_replicas': item['numReadyReplicas'],
      'num_total_replicas': item['numTotalReplicas'],
      'status': item['status'],
      'uid': item['uid'],
    })),
  };
}

export const ResponseListInfrSvcsPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};