/* tslint:disable */
/* eslint-disable */
/**
 * Nested Object Reference Test
 *
 * Test case for nested object reference with recursive FromJSON calls
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type UserProfile, UserProfileFromJSON, UserProfileFromJSONTyped, UserProfileToJSON, instanceOfUserProfile } from './UserProfile';

/** User with required nested profile reference */
export interface UserWithProfile {
  profile: UserProfile,
  userId: string,
}

export function instanceOfUserWithProfile(value: unknown): value is UserWithProfile {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "profile" in value && (value as any)["profile"] !== undefined &&
    "user_id" in value && (value as any)["user_id"] !== undefined;
  const hasAllTsNames =
    "profile" in value && (value as any)["profile"] !== undefined &&
    "userId" in value && (value as any)["userId"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function UserWithProfileFromJSON(json: any): UserWithProfile {
  return UserWithProfileFromJSONTyped(json, false);
}

export function UserWithProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithProfile {
  if (json == null) {
    return json;
  }
  return {
    'profile': UserProfileFromJSON(json['profile']),
    'userId': json['user_id'],
  };
}

export function UserWithProfileToJSON(value?: UserWithProfile | null): any {
  return UserWithProfileToJSONTyped(value, false);
}

export function UserWithProfileToJSONTyped(value?: UserWithProfile | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'profile': UserProfileToJSON(value['profile']),
    'user_id': value['userId'],
  };
}

export const UserWithProfilePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};