/* tslint:disable */
/* eslint-disable */
/**
 * Mixed Property Types Test
 *
 * Test case for object with mix of simple types, arrays, references, and inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface MixedPropertyTypesInlineObject {
  inlineField?: string,
}

export function instanceOfMixedPropertyTypesInlineObject(value: unknown): value is MixedPropertyTypesInlineObject {
  if (!value || typeof value !== "object") {
    return false;
  }
  return true;
}

export function MixedPropertyTypesInlineObjectFromJSON(json: any): MixedPropertyTypesInlineObject {
  return MixedPropertyTypesInlineObjectFromJSONTyped(json, false);
}

export function MixedPropertyTypesInlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): MixedPropertyTypesInlineObject {
  if (json == null) {
    return json;
  }
  return {
    'inlineField': json['inline_field'] ?? undefined,
  };
}

export function MixedPropertyTypesInlineObjectToJSON(value?: MixedPropertyTypesInlineObject | null): any {
  return MixedPropertyTypesInlineObjectToJSONTyped(value, false);
}

export function MixedPropertyTypesInlineObjectToJSONTyped(value?: MixedPropertyTypesInlineObject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'inline_field': value['inlineField'],
  };
}

export const MixedPropertyTypesInlineObjectPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};