// Code generated by openapi-nexus. DO NOT EDIT.
// Array of Inline Objects Test
//
// Test case for array of inline objects with snake_case to camelCase conversion (main case from user issue)
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

// Response containing a list of inference services - main test case for recursive JSON parsing
type ResponseListInfrSvcs struct {
	InferenceServices []string `json:"inference_services"`
}

func (c ResponseListInfrSvcs) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ResponseListInfrSvcs) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"inference_services",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *ResponseListInfrSvcs) GetInferenceServices() []string {
	if c == nil {
		var zero []string
		return zero
	}
	return c.InferenceServices
}

