//! Template function for generating file headers

/// Template function for generating file headers with OpenAPI metadata
pub fn file_header(
    title: Option<String>,
    description: Option<String>,
    version: Option<String>,
) -> String {
    let mut lines = vec![];

    // Add linter disable comments
    lines.push("/* tslint:disable */".to_string());
    lines.push("/* eslint-disable */".to_string());

    // Add OpenAPI documentation block
    lines.push("/**".to_string());

    if let Some(title) = title {
        lines.push(format!(" * {}", title));
    }

    if let Some(description) = description {
        if !lines.is_empty() && lines.last() != Some(&"/**".to_string()) {
            lines.push(" *".to_string());
        }
        // Split description into lines and add them
        for line in description.lines() {
            lines.push(format!(" * {}", line.trim()));
        }
    }

    if let Some(version) = version {
        lines.push(" *".to_string());
        lines.push(format!(
            " * The version of the OpenAPI document: {}",
            version
        ));
    }

    lines.push(" *".to_string());
    lines.push(" * NOTE: This class is auto generated by openapi-nexus.".to_string());
    lines.push(" * https://github.com/adamcavendish/openapi-nexus".to_string());
    lines.push(" * Do not edit the class manually.".to_string());
    lines.push(" */".to_string());

    lines.join("\n")
}
