/* tslint:disable */
/* eslint-disable */
/**
 * Duplicate Parameter Names Test API
 *
 * Test API with duplicate parameter names across different locations
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, VoidApiResponse } from '../runtime/runtime';

export interface ApiCreateItemWithBodyConflictRequest {
    itemId: string;
    queryBody?: string;
    bodyBody: object;
}

/** API client for items operations */

export interface ItemsApiInterface {
  /**
   * Create item with body parameter conflict
   *
   * @param {string} itemId Item ID in path
   * @param {string} queryBody
   * @param {object} bodyBody
   *
   * @throws {RequiredError}
   */
  createItemWithBodyConflictRaw: (requestParameters: ApiCreateItemWithBodyConflictRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<object>>;
  /**
   * Create item with body parameter conflict
   *
   * @param {string} itemId Item ID in path
   * @param {string} queryBody
   * @param {object} bodyBody
   *
   * @throws {RequiredError}
   */
  createItemWithBodyConflict: (requestParameters: ApiCreateItemWithBodyConflictRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<object>;
}

export class ItemsApi extends BaseAPI implements ItemsApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * Create item with body parameter conflict
   *
   * @param {string} itemId Item ID in path
   * @param {string} queryBody
   * @param {object} bodyBody
   *
   * @throws {RequiredError}
   */
  async createItemWithBodyConflictRaw(requestParameters: ApiCreateItemWithBodyConflictRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<object>> {
    if (requestParameters['itemId'] == null) {
      throw new RequiredError(
        'itemId',
        'Required parameter "itemId" was null or undefined when calling createItemWithBodyConflictRaw().'
      );
    }
    if (requestParameters['bodyBody'] == null) {
      throw new RequiredError(
        'bodyBody',
        'Required parameter "bodyBody" was null or undefined when calling createItemWithBodyConflictRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/items/{itemId}`;
    urlPath = urlPath.replace(`{${ 'itemId' }}`, encodeURIComponent(String(requestParameters['itemId'])));
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['queryBody'] !== undefined) {
      queryParameters['body'] = requestParameters['queryBody'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = requestParameters['bodyBody'];
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /**
   * Create item with body parameter conflict
   *
   * @param {string} itemId Item ID in path
   * @param {string} queryBody
   * @param {object} bodyBody
   *
   * @throws {RequiredError}
   */
  async createItemWithBodyConflict(requestParameters: ApiCreateItemWithBodyConflictRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<object> {
    const response = await this.createItemWithBodyConflictRaw(requestParameters, initOverrides);
    return await response.value();
  }
}