/* tslint:disable */
/* eslint-disable */
/**
 * Duplicate Parameter Names Test API
 *
 * Test API with duplicate parameter names across different locations
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, VoidApiResponse } from '../runtime/runtime';

export interface ApiGetUserByIdDuplicateRequest {
    pathId: string;
    queryId?: string;
    headerId?: string;
}

/** API client for users operations */

export interface UsersApiInterface {
  /**
   * Get user by ID with duplicate parameter names
   *
   * @param {string} pathId
   * @param {string} queryId
   * @param {string} headerId
   *
   * @throws {RequiredError}
   */
  getUserByIdDuplicateRaw: (requestParameters: ApiGetUserByIdDuplicateRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<object>>;
  /**
   * Get user by ID with duplicate parameter names
   *
   * @param {string} pathId
   * @param {string} queryId
   * @param {string} headerId
   *
   * @throws {RequiredError}
   */
  getUserByIdDuplicate: (requestParameters: ApiGetUserByIdDuplicateRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<object>;
}

export class UsersApi extends BaseAPI implements UsersApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * Get user by ID with duplicate parameter names
   *
   * @param {string} pathId
   * @param {string} queryId
   * @param {string} headerId
   *
   * @throws {RequiredError}
   */
  async getUserByIdDuplicateRaw(requestParameters: ApiGetUserByIdDuplicateRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<object>> {
    if (requestParameters['pathId'] == null) {
      throw new RequiredError(
        'pathId',
        'Required parameter "pathId" was null or undefined when calling getUserByIdDuplicateRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/users/{id}`;
    urlPath = urlPath.replace(`{${ 'id' }}`, encodeURIComponent(String(requestParameters['pathId'])));
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['queryId'] !== undefined) {
      queryParameters['id'] = requestParameters['queryId'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    if (requestParameters['headerId'] !== undefined) {
      headerParameters['id'] = String(requestParameters['headerId']);
    }
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /**
   * Get user by ID with duplicate parameter names
   *
   * @param {string} pathId
   * @param {string} queryId
   * @param {string} headerId
   *
   * @throws {RequiredError}
   */
  async getUserByIdDuplicate(requestParameters: ApiGetUserByIdDuplicateRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<object> {
    const response = await this.getUserByIdDuplicateRaw(requestParameters, initOverrides);
    return await response.value();
  }
}