/* tslint:disable */
/* eslint-disable */
/**
 * Optional Nested Object Reference Test
 *
 * Test case for optional nested object reference
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
export * from './DefaultApi';
