//! Hardcoded TypeScript-fetch runtime, README, and index files.

use heck::ToKebabCase as _;
use heck::ToPascalCase as _;

use crate::codegen::traits::file_writer::FileInfo;
use crate::ir::types::{IrInfo, IrSpec};

const RUNTIME_TS_BODY: &str = include_str!("project_files/runtime.ts.txt");
const README_MD_BODY: &str = include_str!("project_files/README.md.txt");

/// Render the `@generated` file header used by all generated TypeScript files.
/// Terminates with a trailing newline so callers can concatenate body content
/// directly.
pub fn render_file_header(info: &IrInfo) -> String {
    let mut out = String::new();
    out.push_str("/**\n");
    out.push_str(" * @generated by openapi-nexus. Do not edit.\n");
    out.push_str(" *\n");
    out.push_str(&format!(" * {} — {}\n", info.title, info.version));
    if let Some(desc) = info.description.as_deref()
        && !desc.is_empty()
    {
        for line in desc.lines() {
            out.push_str(&format!(" * {line}\n"));
        }
    }
    out.push_str(" */\n");
    out
}

/// Render one of the re-export index files (`index.ts`, `apis/index.ts`,
/// `models/index.ts`) as header + export statements.
pub fn render_index_file(info: &IrInfo, output_path: &str, exports: &[String]) -> FileInfo {
    let mut content = render_file_header(info);
    for export in exports {
        content.push_str(export);
        content.push('\n');
    }
    FileInfo::project(output_path.to_string(), content)
}

/// Render `runtime/runtime.ts` — fully static except for the base URL.
pub fn render_runtime_file(info: &IrInfo, base_path: &str) -> FileInfo {
    let mut content = render_file_header(info);
    content.push_str(&RUNTIME_TS_BODY.replace("{{BASE_PATH}}", base_path));
    FileInfo::runtime("runtime.ts".to_string(), content)
}

/// Render the top-level `README.md`.
pub fn render_readme_file(ir: &IrSpec) -> FileInfo {
    let title = ir.info.title.as_str();
    let version = ir.info.version.as_str();
    let description = ir
        .info
        .description
        .as_deref()
        .unwrap_or("Generated API client");
    let package_name = title.to_kebab_case();

    let content = README_MD_BODY
        .replace("{{PACKAGE_NAME}}", &package_name)
        .replace("{{DESCRIPTION}}", description)
        .replace("{{VERSION}}", version)
        .replace("{{TITLE}}", title)
        .replace("{{EXAMPLE_API_CLASS}}", &pick_example_api_class(ir));

    FileInfo::readme("README.md".to_string(), content)
}

fn pick_example_api_class(ir: &IrSpec) -> String {
    ir.operations
        .first()
        .and_then(|op| op.tags.first())
        .map(|tag| format!("{}Api", tag.as_str().to_pascal_case()))
        .unwrap_or_else(|| "DefaultApi".to_string())
}
