/* tslint:disable */
/* eslint-disable */
/**
 * Optional Inline Object Test
 *
 * Test case for optional inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface OptionalInlineObjectOptionalConfig {
  settingKey?: string,
  settingValue?: string,
}

export function instanceOfOptionalInlineObjectOptionalConfig(value: unknown): value is OptionalInlineObjectOptionalConfig {
  if (!value || typeof value !== "object") {
    return false;
  }
  return true;
}

export function OptionalInlineObjectOptionalConfigFromJSON(json: any): OptionalInlineObjectOptionalConfig {
  return OptionalInlineObjectOptionalConfigFromJSONTyped(json, false);
}

export function OptionalInlineObjectOptionalConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionalInlineObjectOptionalConfig {
  if (json == null) {
    return json;
  }
  return {
    'settingKey': json['setting_key'] ?? undefined,
    'settingValue': json['setting_value'] ?? undefined,
  };
}

export function OptionalInlineObjectOptionalConfigToJSON(value?: OptionalInlineObjectOptionalConfig | null): any {
  return OptionalInlineObjectOptionalConfigToJSONTyped(value, false);
}

export function OptionalInlineObjectOptionalConfigToJSONTyped(value?: OptionalInlineObjectOptionalConfig | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'setting_key': value['settingKey'],
    'setting_value': value['settingValue'],
  };
}

export const OptionalInlineObjectOptionalConfigPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};