/* tslint:disable */
/* eslint-disable */
/**
 * Array of Inline Objects Test
 *
 * Test case for array of inline objects with snake_case to camelCase conversion (main case from user issue)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, VoidApiResponse } from '../runtime/runtime';

/** API client for default operations */

export interface DefaultApiInterface {
  /** Test endpoint */
  testRaw: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<any>>;
  /** Test endpoint */
  test: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<any>;
}

export class DefaultApi extends BaseAPI implements DefaultApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /** Test endpoint */
  async testRaw(initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<any>> {
    // Build path with path parameters
    let urlPath = `/test`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /** Test endpoint */
  async test(initOverrides?: InitOverrideFunction | RequestInit): Promise<any> {
    const response = await this.testRaw(initOverrides);
    return await response.value();
  }
}