/* tslint:disable */
/* eslint-disable */
/**
 * Simple Type Alias Test
 *
 * Test fixture for simple type aliases (not unions or intersections)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, BlobApiResponse, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, TextApiResponse, VoidApiResponse } from '../runtime/runtime';
import { type Foo, FooFromJSON } from '../models/Foo';

export interface ApiTestSimpleAliasRequest {
    body: Foo;
}

/** API client for default operations */

export interface DefaultApiInterface {
  /**
   * Test endpoint with simple type alias
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  testSimpleAliasRaw: (requestParameters: ApiTestSimpleAliasRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Foo> & { status: 200 } | JSONApiResponse<any> & { status: number }>;
  /**
   * Test endpoint with simple type alias
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  testSimpleAlias: (requestParameters: ApiTestSimpleAliasRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<Foo>;
}

export class DefaultApi extends BaseAPI implements DefaultApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * Test endpoint with simple type alias
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  async testSimpleAliasRaw(requestParameters: ApiTestSimpleAliasRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Foo> & { status: 200 } | JSONApiResponse<any> & { status: number }> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling testSimpleAliasRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/test`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = requestParameters['body'];
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => FooFromJSON(jsonValue)) as JSONApiResponse<Foo> & { status: 200 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Test endpoint with simple type alias
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  async testSimpleAlias(requestParameters: ApiTestSimpleAliasRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<Foo> {
    const response = await this.testSimpleAliasRaw(requestParameters, initOverrides);
    return await response.value();
  }
}