/* tslint:disable */
/* eslint-disable */
/**
 * Empty Array Test
 *
 * Test case for empty array handling
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Object with array that can be empty */
export interface EmptyArrayTest {
  emptyItems: Array<{ itemId: string }>,
}

export function instanceOfEmptyArrayTest(value: object): value is EmptyArrayTest {
  if (!('emptyItems' in value) || (value as any)['emptyItems'] === undefined) return false;
  return true;
}

export function EmptyArrayTestFromJSON(json: any): EmptyArrayTest {
  return EmptyArrayTestFromJSONTyped(json, false);
}

export function EmptyArrayTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmptyArrayTest {
  if (json == null) {
    return json;
  }
  return {
    'emptyItems': json['empty_items'].map((item: any) => ({
      itemId: item['item_id'],
    })),
  };
}

export function EmptyArrayTestToJSON(value?: EmptyArrayTest | null): any {
  return EmptyArrayTestToJSONTyped(value, false);
}

export function EmptyArrayTestToJSONTyped(value?: EmptyArrayTest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'empty_items': value['emptyItems']?.map((item: any) => ({
      'item_id': item['itemId'],
    })),
  };
}

export const EmptyArrayTestPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};