// Code generated by openapi-nexus. DO NOT EDIT.
// Union Type with Interfaces Test
//
// Test fixture for oneOf/anyOf union types with interface members
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

type Baz struct {
	Path string `json:"path"`
	Type string `json:"type"`
}

func (c Baz) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Baz) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"type",
		"path",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *Baz) GetPath() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Path
}

func (c *Baz) GetType() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Type
}

