/* tslint:disable */
/* eslint-disable */
/**
 * Petstore API
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
/** Category model */
export interface Category {
  id?: number | null,
  name?: string | null,
}

export function instanceOfCategory(value: object): value is Category {
  return true;
}

export function CategoryFromJSON(json: any): Category {
    return CategoryFromJSONTyped(json, false);
}

export function CategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Category {
  if (json == null) {
    return json;
  }
  return {
   'id': json['id'] ?? undefined,
   'name': json['name'] ?? undefined,
  };
}

export function CategoryToJSON(value?: Category | null): any {
    return CategoryToJSONTyped(value, false);
}

export function CategoryToJSONTyped(value?: Category | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
   'id': value['id'],
   'name': value['name'],
  };
}

export const CategoryPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
};