/* tslint:disable */
/* eslint-disable */
/**
 * Petstore API
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import type { PetStatus } from './PetStatus';
import { PetStatusFromJSON, PetStatusToJSON } from './PetStatus';
import type { Tag } from './Tag';
import { TagFromJSON, TagToJSON } from './Tag';
import type { Category } from './Category';
import { CategoryFromJSON, CategoryToJSON } from './Category';

/** Pet model */
export interface Pet {
  category?: null | Category,
  id?: number | null,
  name: string,
  photoUrls: Array<string>,
  status?: null | PetStatus,
  tags?: Array<Tag>,
}

export function instanceOfPet(value: object): value is Pet {
  if (!('name' in value) || (value as any)['name'] === undefined) return false;
  if (!('photoUrls' in value) || (value as any)['photoUrls'] === undefined) return false;
  return true;
}

export function PetFromJSON(json: any): Pet {
  return PetFromJSONTyped(json, false);
}

export function PetFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pet {
  if (json == null) {
    return json;
  }
  return {
    'category': json['category'] ?? undefined,
    'id': json['id'] ?? undefined,
    'name': json['name'],
    'photoUrls': json['photo_urls'],
    'status': json['status'] ?? undefined,
    'tags': json['tags']?.map((item: any) => TagFromJSON(item)) ?? undefined,
  };
}

export function PetToJSON(value?: Pet | null): any {
  return PetToJSONTyped(value, false);
}

export function PetToJSONTyped(value?: Pet | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'category': value['category'],
    'id': value['id'],
    'name': value['name'],
    'photo_urls': value['photoUrls'],
    'status': value['status'],
    'tags': value['tags']?.map((item: any) => TagToJSON(item)),
  };
}

export const PetPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};