/* tslint:disable */
/* eslint-disable */
/**
 * Petstore API
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
/** Tag model */
export interface Tag {
  id?: number | null,
  name?: string | null,
}

export function instanceOfTag(value: object): value is Tag {
  return true;
}

export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
  if (json == null) {
    return json;
  }
  return {
   'id': json['id'] ?? undefined,
   'name': json['name'] ?? undefined,
  };
}

export function TagToJSON(value?: Tag | null): any {
    return TagToJSONTyped(value, false);
}

export function TagToJSONTyped(value?: Tag | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
   'id': value['id'],
   'name': value['name'],
  };
}

export const TagPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
};