/* tslint:disable */
/* eslint-disable */
/**
 * Petstore API
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Upload response model */
export interface UploadResponse {
  code?: number | null,
  message?: string | null,
  type?: string | null,
}

export function instanceOfUploadResponse(value: object): value is UploadResponse {
  return true;
}

export function UploadResponseFromJSON(json: any): UploadResponse {
  return UploadResponseFromJSONTyped(json, false);
}

export function UploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadResponse {
  if (json == null) {
    return json;
  }
  return {
    'code': json['code'] ?? undefined,
    'message': json['message'] ?? undefined,
    'type': json['type'] ?? undefined,
  };
}

export function UploadResponseToJSON(value?: UploadResponse | null): any {
  return UploadResponseToJSONTyped(value, false);
}

export function UploadResponseToJSONTyped(value?: UploadResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'code': value['code'],
    'message': value['message'],
    'type': value['type'],
  };
}

export const UploadResponsePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};