/* tslint:disable */
/* eslint-disable */
/**
 * Test API with Server Objects
 *
 * This is a test API specification that includes various server configurations
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, JSONApiResponse, VoidApiResponse, ResponseError, RequiredError, DefaultConfig, type Configuration, type InitOverrideFunction } from '../runtime/runtime';

export interface ApiGetUserByIdRequest {
    id: string;
}

/** API client for default operations */

export interface DefaultApiInterface {
  /** Get all users */
  getAllUsersRaw: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Array<object>>>;
  /**
   * Get user by ID
   *
   * @param {string} id User ID
   *
   * @throws {RequiredError}
   */
  getUserByIdRaw: (requestParameters: ApiGetUserByIdRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<object>>;
  /** Get all users */
  getAllUsers: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<Array<object>>;
  /**
   * Get user by ID
   *
   * @param {string} id User ID
   *
   * @throws {RequiredError}
   */
  getUserById: (requestParameters: ApiGetUserByIdRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<object>;
}

export class DefaultApi extends BaseAPI implements DefaultApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /** Get all users */
  async getAllUsersRaw(initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Array<object>>> {
    // Build path with path parameters
    let urlPath = `/users`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /** Get all users */
  async getAllUsers(initOverrides?: InitOverrideFunction | RequestInit): Promise<Array<object>> {
    const response = await this.getAllUsersRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get user by ID
   *
   * @param {string} id User ID
   *
   * @throws {RequiredError}
   */
  async getUserByIdRaw(requestParameters: ApiGetUserByIdRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<object>> {
    if (requestParameters['id'] == null) {
      throw new RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getUserByIdRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/users/{id}`;
    urlPath = urlPath.replace(`{${ 'id' }}`, encodeURIComponent(String(requestParameters['id'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /**
   * Get user by ID
   *
   * @param {string} id User ID
   *
   * @throws {RequiredError}
   */
  async getUserById(requestParameters: ApiGetUserByIdRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<object> {
    const response = await this.getUserByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }
}