// Code generated by openapi-nexus. DO NOT EDIT.
// Petstore API
//
// This is a sample Pet Store Server based on the OpenAPI 3.1 specification
//
// Generated from OpenAPI doc version 1.0.0

package operations

import (
	"example.com/sdk/internal/config"
	"example.com/sdk/internal/hooks"
	"example.com/sdk/internal/utils"
	"example.com/sdk/models/components"
	"example.com/sdk/models/operations"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

// Store - store operations
type Store struct {
	rootSDK          *PetstoreApiSDK
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newStore(rootSDK *PetstoreApiSDK, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *Store {
	return &Store{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
	}
}

// GetInventory - GET /store/inventory
func (s *Store) GetInventory(
	ctx context.Context,
	opts ...operations.Option,
) (*operations.GetInventoryResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/store/inventory")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "get_inventory",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.GetInventoryResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// PlaceOrder - POST /store/order
func (s *Store) PlaceOrder(
	ctx context.Context,
	request components.PlaceOrderRequest,
	opts ...operations.Option,
) (*operations.PlaceOrderResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/store/order")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "place_order",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	bodyReader, reqContentType, err := utils.SerializeRequestBody(ctx, request, false, false, "Request", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "POST", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.PlaceOrderResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// GetOrderById - GET /store/order/{orderId}
func (s *Store) GetOrderById(
	ctx context.Context,
	pathOrderId string,
	opts ...operations.Option,
) (*operations.GetOrderByIdResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/store/order/{orderId}")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}

	// Build path parameters
	pathParams := map[string]string{
		"orderId": fmt.Sprintf("%v", pathOrderId),
	}
	opURL = utils.ReplaceParameters(opURL, pathParams)

	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "get_order_by_id",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.GetOrderByIdResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// DeleteOrder - DELETE /store/order/{orderId}
func (s *Store) DeleteOrder(
	ctx context.Context,
	pathOrderId string,
	opts ...operations.Option,
) (*operations.DeleteOrderResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/store/order/{orderId}")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}

	// Build path parameters
	pathParams := map[string]string{
		"orderId": fmt.Sprintf("%v", pathOrderId),
	}
	opURL = utils.ReplaceParameters(opURL, pathParams)

	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "delete_order",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "DELETE", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.DeleteOrderResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

