// Code generated by openapi-nexus. DO NOT EDIT.
// Petstore API
//
// This is a sample Pet Store Server based on the OpenAPI 3.1 specification
//
// Generated from OpenAPI doc version 1.0.0

package operations

import (
	"example.com/sdk/internal/config"
	"example.com/sdk/internal/hooks"
	"example.com/sdk/internal/utils"
	"example.com/sdk/models/components"
	"example.com/sdk/models/operations"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
)

// User - user operations
type User struct {
	rootSDK          *PetstoreApiSDK
	sdkConfiguration config.SDKConfiguration
	hooks            *hooks.Hooks
}

func newUser(rootSDK *PetstoreApiSDK, sdkConfig config.SDKConfiguration, hooks *hooks.Hooks) *User {
	return &User{
		rootSDK:          rootSDK,
		sdkConfiguration: sdkConfig,
		hooks:            hooks,
	}
}

// CreateUser - POST /user
func (s *User) CreateUser(
	ctx context.Context,
	request components.CreateUserRequest,
	opts ...operations.Option,
) (*operations.CreateUserResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/user")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "create_user",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	bodyReader, reqContentType, err := utils.SerializeRequestBody(ctx, request, false, false, "Request", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "POST", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.CreateUserResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// CreateUsersWithListInput - POST /user/createWithList
func (s *User) CreateUsersWithListInput(
	ctx context.Context,
	request components.CreateUsersWithListInputRequest,
	opts ...operations.Option,
) (*operations.CreateUsersWithListInputResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/user/createWithList")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "create_users_with_list_input",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	bodyReader, reqContentType, err := utils.SerializeRequestBody(ctx, request, false, false, "Request", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "POST", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.CreateUsersWithListInputResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// LoginUser - GET /user/login
func (s *User) LoginUser(
	ctx context.Context,
	queryUsername string,
	queryPassword string,
	opts ...operations.Option,
) (*operations.LoginUserResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/user/login")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "login_user",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}

	// Build query parameters
	queryParams := struct {
		Username string `queryParam:"name=username,style=form,explode=true"`
		Password string `queryParam:"name=password,style=form,explode=true"`
	}{
		Username: queryUsername,
		Password: queryPassword,
	}
	if err := utils.PopulateQueryParams(ctx, req, queryParams, nil); err != nil {
		return nil, err
	}


	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.LoginUserResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// LogoutUser - GET /user/logout
func (s *User) LogoutUser(
	ctx context.Context,
	opts ...operations.Option,
) (*operations.LogoutUserResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/user/logout")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}


	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "logout_user",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.LogoutUserResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// GetUserByName - GET /user/{username}
func (s *User) GetUserByName(
	ctx context.Context,
	pathUsername string,
	opts ...operations.Option,
) (*operations.GetUserByNameResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/user/{username}")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}

	// Build path parameters
	pathParams := map[string]string{
		"username": fmt.Sprintf("%v", pathUsername),
	}
	opURL = utils.ReplaceParameters(opURL, pathParams)

	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "get_user_by_name",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "GET", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.GetUserByNameResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// UpdateUser - PUT /user/{username}
func (s *User) UpdateUser(
	ctx context.Context,
	pathUsername string,
	request components.UpdateUserRequest,
	opts ...operations.Option,
) (*operations.UpdateUserResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/user/{username}")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}

	// Build path parameters
	pathParams := map[string]string{
		"username": fmt.Sprintf("%v", pathUsername),
	}
	opURL = utils.ReplaceParameters(opURL, pathParams)

	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "update_user",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	bodyReader, reqContentType, err := utils.SerializeRequestBody(ctx, request, false, false, "Request", "json", `request:"mediaType=application/json"`)
	if err != nil {
		return nil, err
	}

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "PUT", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.UpdateUserResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

// DeleteUser - DELETE /user/{username}
func (s *User) DeleteUser(
	ctx context.Context,
	pathUsername string,
	opts ...operations.Option,
) (*operations.DeleteUserResponse, error) {
	o := operations.Options{}
	supportedOptions := []string{
		operations.SupportedOptionRetries,
		operations.SupportedOptionTimeout,
	}

	for _, opt := range opts {
		if err := opt(&o, supportedOptions...); err != nil {
			return nil, fmt.Errorf("error applying option: %w", err)
		}
	}

	var baseURL string
	if o.ServerURL == nil {
		baseURL, _ = s.sdkConfiguration.GetServerDetails()
	} else {
		baseURL = *o.ServerURL
	}
	opURL, err := url.JoinPath(baseURL, "/user/{username}")
	if err != nil {
		return nil, fmt.Errorf("error generating URL: %w", err)
	}

	// Build path parameters
	pathParams := map[string]string{
		"username": fmt.Sprintf("%v", pathUsername),
	}
	opURL = utils.ReplaceParameters(opURL, pathParams)

	hookCtx := hooks.HookContext{
		SDK:              s.rootSDK,
		SDKConfiguration: s.sdkConfiguration,
		BaseURL:          baseURL,
		Context:          ctx,
		OperationID:      "delete_user",
		OAuth2Scopes:     nil,
		SecuritySource:   nil,
	}

	var bodyReader io.Reader = nil
	var reqContentType string = ""

	timeout := o.Timeout
	if timeout == nil {
		timeout = s.sdkConfiguration.Timeout
	}

	if timeout != nil {
		var cancel context.CancelFunc
		ctx, cancel = context.WithTimeout(ctx, *timeout)
		defer cancel()
	}

	req, err := http.NewRequestWithContext(ctx, "DELETE", opURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("error creating request: %w", err)
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("User-Agent", s.sdkConfiguration.UserAgent)
	if reqContentType != "" {
		req.Header.Set("Content-Type", reqContentType)
	}



	for k, v := range o.SetHeaders {
		req.Header.Set(k, v)
	}

	globalRetryConfig := s.sdkConfiguration.RetryConfig
	retryConfig := o.Retries
	if retryConfig == nil {
		retryConfig = globalRetryConfig
	}

	httpRes, err := utils.Retry(ctx, utils.Retries{
		Config:      retryConfig,
		StatusCodes: []string{"5XX"},
	}, func() (*http.Response, error) {
		if req.Body != nil {
			copyBody, err := req.GetBody()
			if err != nil {
				return nil, err
			}
			req.Body = copyBody
		}

		req, err = s.hooks.BeforeRequest(hooks.BeforeRequestContext{HookContext: hookCtx}, req)
		if err != nil {
			return nil, err
		}

		httpRes, err := s.sdkConfiguration.Client.Do(req)
		if err != nil || httpRes == nil {
			if err != nil {
				hookCtx := hooks.AfterErrorContext{HookContext: hookCtx}
				httpRes, err = s.hooks.AfterError(hookCtx, httpRes, err)
			}
			return httpRes, err
		}

		httpRes, err = s.hooks.AfterSuccess(hooks.AfterSuccessContext{HookContext: hookCtx}, httpRes)
		if err != nil {
			return httpRes, err
		}

		return httpRes, nil
	})
	if err != nil {
		return nil, err
	}

	defer httpRes.Body.Close()

	res := &operations.DeleteUserResponse{
		HTTPMeta: components.HTTPMetadata{
			Response: httpRes,
		},
	}

	switch {
	case utils.MatchStatusCodes([]string{"200"}, httpRes.StatusCode):
		// TODO: Parse response body based on content type
	default:
		rawBody, err := utils.ConsumeRawBody(httpRes)
		if err != nil {
			return nil, err
		}
		httpRes.Body.Close()
		return nil, fmt.Errorf("error: status code %d, body: %s", httpRes.StatusCode, string(rawBody))
	}

	return res, nil
}

