// Code generated by openapi-nexus. DO NOT EDIT.
// Primitive Array Test
//
// Test case for arrays with primitive items (should not be affected by recursive parsing)
//
// Generated from OpenAPI doc version 1.0.0

package sdk

// TODO: Implement main SDK file
