//! Stage A: prove `sigil_emit::generate_model_files` handles Object + Enum +
//! Alias together without hand-matching kinds at the call site.
//!
//! Asserts the emitted TS shape loosely (contains …) rather than byte-for-byte
//! — goldens land after Stage C when the whole kind surface is stable.

use std::fs;
use std::path::Path;

use openapi_nexus::generators::typescript::fetch::sigil_emit;

fn read_fixture(rel: &str) -> String {
    for base in [
        "tests/fixtures",
        "../tests/fixtures",
        "../../tests/fixtures",
        "../../../tests/fixtures",
    ] {
        let p = Path::new(base).join(rel);
        if p.exists() {
            return fs::read_to_string(p).unwrap();
        }
    }
    panic!("fixture not found: {rel}");
}

fn render_models(fixture: &str) -> Vec<(String, String)> {
    let yaml = read_fixture(fixture);
    let parsed = openapi_nexus::parser::parse_content_yaml(&yaml).unwrap();
    let ir = openapi_nexus::ir::lower::lower(parsed).unwrap();
    sigil_emit::generate_model_files(&ir)
        .expect("all kinds in fixture should be supported")
        .into_iter()
        .map(|f| (f.filename, f.content))
        .collect()
}

fn find<'a>(files: &'a [(String, String)], filename: &str) -> &'a str {
    files
        .iter()
        .find(|(n, _)| n == filename)
        .map(|(_, c)| c.as_str())
        .unwrap_or_else(|| {
            panic!(
                "expected file {filename} in: {:?}",
                files.iter().map(|(n, _)| n).collect::<Vec<_>>()
            )
        })
}

#[test]
fn simple_type_alias_renders_primitives_and_array() {
    let files = render_models("valid/type-aliases/simple-type-alias.yaml");

    let foo = find(&files, "Foo.ts");
    assert!(
        foo.contains("export type Foo = string;"),
        "expected string alias, got:\n{foo}"
    );
    assert!(
        foo.contains("A simple string type alias"),
        "expected description in:\n{foo}"
    );

    let bar = find(&files, "Bar.ts");
    assert!(
        bar.contains("export type Bar = number;"),
        "expected number alias, got:\n{bar}"
    );

    let baz = find(&files, "Baz.ts");
    assert!(
        baz.contains("export type Baz = readonly string[];"),
        "expected readonly array alias, got:\n{baz}"
    );
}

#[test]
fn mixed_object_and_enum_dispatch_in_one_spec() {
    let files = render_models("valid/interface-with-enum-reference.yaml");

    let foo_type = find(&files, "FooType.ts");
    assert!(
        foo_type.contains("export type FooType = 'foo' | 'bar' | 'baz';"),
        "expected string-enum union alias, got:\n{foo_type}"
    );

    let foo_specs = find(&files, "FooSpecs.ts");
    assert!(
        foo_specs.contains("export interface FooSpecs"),
        "expected interface, got:\n{foo_specs}"
    );
    assert!(
        foo_specs.contains("readonly fooType: FooType"),
        "expected field referencing FooType, got:\n{foo_specs}"
    );
    assert!(
        foo_specs.contains("import type { FooType } from './FooType';"),
        "expected import of FooType, got:\n{foo_specs}"
    );

    let bar_service = find(&files, "BarService.ts");
    assert!(
        bar_service.contains("export interface BarService"),
        "expected BarService interface, got:\n{bar_service}"
    );
    assert!(
        bar_service.contains("readonly status: BarStatus"),
        "expected BarService.status: BarStatus, got:\n{bar_service}"
    );
}

#[test]
fn header_prepended_to_each_file() {
    let files = render_models("valid/type-aliases/simple-type-alias.yaml");
    for (name, content) in &files {
        assert!(
            content.starts_with("/**\n * @generated by openapi-nexus. Do not edit."),
            "{name} missing @generated header:\n{content}"
        );
        assert!(
            content.contains("Simple Type Alias Test — 1.0.0"),
            "{name} missing title/version line:\n{content}"
        );
    }
}
