// Code generated by openapi-nexus. DO NOT EDIT.
// Optional Inline Object Test
//
// Test case for optional inline objects
//
// Generated from OpenAPI doc version 1.0.0

package sdk

// TODO: Implement main SDK file
