// Code generated by openapi-nexus. DO NOT EDIT.
// Optional Nested Object Reference Test
//
// Test case for optional nested object reference
//
// Generated from OpenAPI doc version 1.0.0

package sdk

// TODO: Implement main SDK file
