/* tslint:disable */
/* eslint-disable */
/**
 * Complex Union Type Test
 *
 * Test fixture for complex union types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface Qux {
  namespace: string,
  type: "qux",
  url: string,
}

export function instanceOfQux(value: unknown): value is Qux {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "namespace" in value && (value as any)["namespace"] !== undefined &&
    "type" in value && (value as any)["type"] !== undefined &&
    "url" in value && (value as any)["url"] !== undefined;
  const hasAllTsNames =
    "namespace" in value && (value as any)["namespace"] !== undefined &&
    "type" in value && (value as any)["type"] !== undefined &&
    "url" in value && (value as any)["url"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function QuxFromJSON(json: any): Qux {
  return QuxFromJSONTyped(json, false);
}

export function QuxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Qux {
  if (json == null) {
    return json;
  }
  return {
    'namespace': json['namespace'],
    'type': json['type'],
    'url': json['url'],
  };
}

export function QuxToJSON(value?: Qux | null): any {
  return QuxToJSONTyped(value, false);
}

export function QuxToJSONTyped(value?: Qux | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'namespace': value['namespace'],
    'type': value['type'],
    'url': value['url'],
  };
}

export const QuxPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};