/* tslint:disable */
/* eslint-disable */
/**
 * Complex Union Type Test
 *
 * Test fixture for complex union types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface Baz {
  path: string,
  type: "baz",
}

export function instanceOfBaz(value: object): value is Baz {
  if (!('path' in value) || (value as any)['path'] === undefined) return false;
  if (!('type' in value) || (value as any)['type'] === undefined) return false;
  return true;
}

export function BazFromJSON(json: any): Baz {
  return BazFromJSONTyped(json, false);
}

export function BazFromJSONTyped(json: any, ignoreDiscriminator: boolean): Baz {
  if (json == null) {
    return json;
  }
  return {
    'path': json['path'],
    'type': json['type'],
  };
}

export function BazToJSON(value?: Baz | null): any {
  return BazToJSONTyped(value, false);
}

export function BazToJSONTyped(value?: Baz | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'path': value['path'],
    'type': value['type'],
  };
}

export const BazPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};