/* tslint:disable */
/* eslint-disable */
/**
 * Complex Union Type Test
 *
 * Test fixture for complex union types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type Bar, BarFromJSON, BarFromJSONTyped, BarToJSON, instanceOfBar } from './Bar';
import { type Baz, BazFromJSON, BazFromJSONTyped, BazToJSON, instanceOfBaz } from './Baz';
import { type Qux, QuxFromJSON, QuxFromJSONTyped, QuxToJSON, instanceOfQux } from './Qux';

export type Foo = Bar | Baz | Qux

export function FooFromJSON(json: any): Foo {
  return FooFromJSONTyped(json, false);
}

export function FooFromJSONTyped(json: any, ignoreDiscriminator: boolean): Foo {
  if (json == null) {
    return json;
  }
  if (typeof json !== 'object') {
    return json;
  }
  if (instanceOfBar(json)) {
    return BarFromJSONTyped(json, true);
  }
  if (instanceOfBaz(json)) {
    return BazFromJSONTyped(json, true);
  }
  if (instanceOfQux(json)) {
    return QuxFromJSONTyped(json, true);
  }
  return {} as any;
}

export function FooToJSON(value?: Foo | null): any {
  return FooToJSONTyped(value, false);
}

export function FooToJSONTyped(value?: Foo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  if (typeof value !== 'object') {
    return value;
  }
  if (instanceOfBar(value)) {
    return BarToJSON(value as Bar);
  }
  if (instanceOfBaz(value)) {
    return BazToJSON(value as Baz);
  }
  if (instanceOfQux(value)) {
    return QuxToJSON(value as Qux);
  }
  return {};
}