/* tslint:disable */
/* eslint-disable */
/**
 * Complex Union Type Test
 *
 * Test fixture for complex union types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
export * from './Bar';
export * from './Baz';
export * from './Foo';
export * from './Quux';
export * from './Qux';
