/* tslint:disable */
/* eslint-disable */
/**
 * Complex Union Type Test
 *
 * Test fixture for complex union types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type Foo, FooFromJSON, FooFromJSONTyped, FooToJSON } from './Foo';

export interface Quux {
  foo: Foo,
  name: string,
}

export function instanceOfQuux(value: unknown): value is Quux {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "foo" in value && (value as any)["foo"] !== undefined &&
    "name" in value && (value as any)["name"] !== undefined;
  const hasAllTsNames =
    "foo" in value && (value as any)["foo"] !== undefined &&
    "name" in value && (value as any)["name"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function QuuxFromJSON(json: any): Quux {
  return QuuxFromJSONTyped(json, false);
}

export function QuuxFromJSONTyped(json: any, ignoreDiscriminator: boolean): Quux {
  if (json == null) {
    return json;
  }
  return {
    'foo': FooFromJSON(json['foo']),
    'name': json['name'],
  };
}

export function QuuxToJSON(value?: Quux | null): any {
  return QuuxToJSONTyped(value, false);
}

export function QuuxToJSONTyped(value?: Quux | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'foo': FooToJSON(value['foo']),
    'name': value['name'],
  };
}

export const QuuxPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};