/* tslint:disable */
/* eslint-disable */
/**
 * Optional Array of Referenced Types Test
 *
 * Test case for optional array of referenced model types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
/** Object with optional array of User references */
export interface OptionalUserList {
  optionalUsers?: Array<User>,
}

export function instanceOfOptionalUserList(value: object): value is OptionalUserList {
  return true;
}

export function OptionalUserListFromJSON(json: any): OptionalUserList {
  return OptionalUserListFromJSONTyped(json, false);
}

export function OptionalUserListFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptionalUserList {
  if (json == null) {
    return json;
  }
  return {
    'optionalUsers': json['optional_users']?.map((item: any) => UserFromJSON(item)) ?? undefined,
  };
}

export function OptionalUserListToJSON(value?: OptionalUserList | null): any {
  return OptionalUserListToJSONTyped(value, false);
}

export function OptionalUserListToJSONTyped(value?: OptionalUserList | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'optional_users': value['optionalUsers']?.map((item: any) => UserToJSON(item)),
  };
}

export const OptionalUserListPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};