/* tslint:disable */
/* eslint-disable */
/**
 * Inline Object Test
 *
 * Test case for inline objects (not arrays) with snake_case to camelCase conversion
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type InlineObjectTestConfig, InlineObjectTestConfigFromJSON, InlineObjectTestConfigFromJSONTyped, InlineObjectTestConfigToJSON, instanceOfInlineObjectTestConfig } from './InlineObjectTestConfig';
import { type InlineObjectTestMetadata, InlineObjectTestMetadataFromJSON, InlineObjectTestMetadataFromJSONTyped, InlineObjectTestMetadataToJSON, instanceOfInlineObjectTestMetadata } from './InlineObjectTestMetadata';

/** Object with inline object properties */
export interface InlineObjectTest {
  config?: InlineObjectTestConfig,
  metadata: InlineObjectTestMetadata,
}

export function instanceOfInlineObjectTest(value: unknown): value is InlineObjectTest {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "metadata" in value && (value as any)["metadata"] !== undefined;
  const hasAllTsNames =
    "metadata" in value && (value as any)["metadata"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function InlineObjectTestFromJSON(json: any): InlineObjectTest {
  return InlineObjectTestFromJSONTyped(json, false);
}

export function InlineObjectTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObjectTest {
  if (json == null) {
    return json;
  }
  return {
    'config': InlineObjectTestConfigFromJSON(json['config']) ?? undefined,
    'metadata': InlineObjectTestMetadataFromJSON(json['metadata']),
  };
}

export function InlineObjectTestToJSON(value?: InlineObjectTest | null): any {
  return InlineObjectTestToJSONTyped(value, false);
}

export function InlineObjectTestToJSONTyped(value?: InlineObjectTest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'config': InlineObjectTestConfigToJSON(value['config']),
    'metadata': InlineObjectTestMetadataToJSON(value['metadata']),
  };
}

export const InlineObjectTestPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};