/* tslint:disable */
/* eslint-disable */
/**
 * Inline Object Test
 *
 * Test case for inline objects (not arrays) with snake_case to camelCase conversion
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
/** Object with inline object properties */
export interface InlineObjectTest {
  config?: { maxRetryCount: number; timeoutSeconds: number },
  metadata: { createdAt: string; updatedAt: string; versionNumber: number },
}

export function instanceOfInlineObjectTest(value: object): value is InlineObjectTest {
  if (!('metadata' in value) || (value as any)['metadata'] === undefined) return false;
  return true;
}

export function InlineObjectTestFromJSON(json: any): InlineObjectTest {
  return InlineObjectTestFromJSONTyped(json, false);
}

export function InlineObjectTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObjectTest {
  if (json == null) {
    return json;
  }
  return {
    'config': json['config'] ? {
      maxRetryCount: json['config']['max_retry_count'],
      timeoutSeconds: json['config']['timeout_seconds'],
    } : undefined,
    'metadata': json['metadata'] ? {
      createdAt: json['metadata']['created_at'],
      updatedAt: json['metadata']['updated_at'],
      versionNumber: json['metadata']['version_number'],
    } : {},
  };
}

export function InlineObjectTestToJSON(value?: InlineObjectTest | null): any {
  return InlineObjectTestToJSONTyped(value, false);
}

export function InlineObjectTestToJSONTyped(value?: InlineObjectTest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'config': value['config'] ? {
      'max_retry_count': value['config']['maxRetryCount'],
      'timeout_seconds': value['config']['timeoutSeconds'],
    } : undefined,
    'metadata': value['metadata'] ? {
      'created_at': value['metadata']['createdAt'],
      'updated_at': value['metadata']['updatedAt'],
      'version_number': value['metadata']['versionNumber'],
    } : undefined,
  };
}

export const InlineObjectTestPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};