/* tslint:disable */
/* eslint-disable */
/**
 * Inline Object Test
 *
 * Test case for inline objects (not arrays) with snake_case to camelCase conversion
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface InlineObjectTestMetadata {
  createdAt: string,
  updatedAt?: string,
  versionNumber?: number,
}

export function instanceOfInlineObjectTestMetadata(value: object): value is InlineObjectTestMetadata {
  if (!('createdAt' in value) || (value as any)['createdAt'] === undefined) return false;
  return true;
}

export function InlineObjectTestMetadataFromJSON(json: any): InlineObjectTestMetadata {
  return InlineObjectTestMetadataFromJSONTyped(json, false);
}

export function InlineObjectTestMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObjectTestMetadata {
  if (json == null) {
    return json;
  }
  return {
    'createdAt': json['created_at'],
    'updatedAt': json['updated_at'] ?? undefined,
    'versionNumber': json['version_number'] ?? undefined,
  };
}

export function InlineObjectTestMetadataToJSON(value?: InlineObjectTestMetadata | null): any {
  return InlineObjectTestMetadataToJSONTyped(value, false);
}

export function InlineObjectTestMetadataToJSONTyped(value?: InlineObjectTestMetadata | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'created_at': value['createdAt'],
    'updated_at': value['updatedAt'],
    'version_number': value['versionNumber'],
  };
}

export const InlineObjectTestMetadataPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};