/* tslint:disable */
/* eslint-disable */
/**
 * Inline Object Test
 *
 * Test case for inline objects (not arrays) with snake_case to camelCase conversion
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface InlineObjectTestConfig {
  maxRetryCount?: number,
  timeoutSeconds?: number,
}

export function instanceOfInlineObjectTestConfig(value: object): value is InlineObjectTestConfig {
  return true;
}

export function InlineObjectTestConfigFromJSON(json: any): InlineObjectTestConfig {
  return InlineObjectTestConfigFromJSONTyped(json, false);
}

export function InlineObjectTestConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObjectTestConfig {
  if (json == null) {
    return json;
  }
  return {
    'maxRetryCount': json['max_retry_count'] ?? undefined,
    'timeoutSeconds': json['timeout_seconds'] ?? undefined,
  };
}

export function InlineObjectTestConfigToJSON(value?: InlineObjectTestConfig | null): any {
  return InlineObjectTestConfigToJSONTyped(value, false);
}

export function InlineObjectTestConfigToJSONTyped(value?: InlineObjectTestConfig | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'max_retry_count': value['maxRetryCount'],
    'timeout_seconds': value['timeoutSeconds'],
  };
}

export const InlineObjectTestConfigPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};