// Code generated by openapi-nexus. DO NOT EDIT.
// Nested Union Type Test
//
// Test fixture for union types that reference other union types
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

type Bar struct {
	Endpoint string `json:"endpoint"`
	Type string `json:"type"`
}

func (c Bar) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Bar) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"type",
		"endpoint",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *Bar) GetEndpoint() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Endpoint
}

func (c *Bar) GetType() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Type
}

