/* tslint:disable */
/* eslint-disable */
/**
 * Optional Nested Object Reference Test
 *
 * Test case for optional nested object reference
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import type { UserProfile } from './UserProfile';
import { UserProfileFromJSON, UserProfileToJSON } from './UserProfile';

/** User with optional nested profile reference */
export interface UserWithOptionalProfile {
  optionalProfile?: UserProfile,
  userId: string,
}

export function instanceOfUserWithOptionalProfile(value: object): value is UserWithOptionalProfile {
  if (!('userId' in value) || (value as any)['userId'] === undefined) return false;
  return true;
}

export function UserWithOptionalProfileFromJSON(json: any): UserWithOptionalProfile {
  return UserWithOptionalProfileFromJSONTyped(json, false);
}

export function UserWithOptionalProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithOptionalProfile {
  if (json == null) {
    return json;
  }
  return {
    'optionalProfile': UserProfileFromJSON(json['optional_profile']) ?? undefined,
    'userId': json['user_id'],
  };
}

export function UserWithOptionalProfileToJSON(value?: UserWithOptionalProfile | null): any {
  return UserWithOptionalProfileToJSONTyped(value, false);
}

export function UserWithOptionalProfileToJSONTyped(value?: UserWithOptionalProfile | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'optional_profile': UserProfileToJSON(value['optionalProfile']),
    'user_id': value['userId'],
  };
}

export const UserWithOptionalProfilePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};