/* tslint:disable */
/* eslint-disable */
/**
 * Array with Reference Property Test
 *
 * Test case for array of inline objects that contain a reference property
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** User model with snake_case properties */
export interface User {
  emailAddress?: string,
  userId: string,
  userName: string,
}

export function instanceOfUser(value: object): value is User {
  if (!('userId' in value) || (value as any)['userId'] === undefined) return false;
  if (!('userName' in value) || (value as any)['userName'] === undefined) return false;
  return true;
}

export function UserFromJSON(json: any): User {
  return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
  if (json == null) {
    return json;
  }
  return {
    'emailAddress': json['email_address'] ?? undefined,
    'userId': json['user_id'],
    'userName': json['user_name'],
  };
}

export function UserToJSON(value?: User | null): any {
  return UserToJSONTyped(value, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'email_address': value['emailAddress'],
    'user_id': value['userId'],
    'user_name': value['userName'],
  };
}

export const UserPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};