// Code generated by openapi-nexus. DO NOT EDIT.
// Array of Referenced Types Test
//
// Test case for array of referenced model types with recursive FromJSON calls
//
// Generated from OpenAPI doc version 1.0.0

package sdk

// TODO: Implement main SDK file
