/* tslint:disable */
/* eslint-disable */
/**
 * Naming Conventions Test
 *
 * Test fixture to verify language property naming conventions
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, VoidApiResponse } from '../runtime/runtime';
import { type NamingConventionTest, NamingConventionTestFromJSON, NamingConventionTestToJSON } from '../models/NamingConventionTest';

export interface ApiGetWithQueryParamsRequest {
    snakeCaseParam: string;
    snakeCaseNumber?: string;
    kebabCaseParam?: string;
    kebabCaseArray?: Array<string>;
    pascalCaseParam?: string;
    pascalCaseNumber?: string;
    screamingSnakeCase?: string;
    screamingNumber?: string;
    camelCaseParam?: string;
    camelCaseNumber?: string;
    singleword?: string;
    id?: string;
}

export interface ApiTestNamingConventionsRequest {
    body: NamingConventionTest;
}

/** API client for default operations */

export interface DefaultApiInterface {
  /**
   * Get with query parameters
   *
   * @param {string} snakeCaseParam
   * @param {string} snakeCaseNumber
   * @param {string} kebabCaseParam
   * @param {Array<string>} kebabCaseArray
   * @param {string} pascalCaseParam
   * @param {string} pascalCaseNumber
   * @param {string} screamingSnakeCase
   * @param {string} screamingNumber
   * @param {string} camelCaseParam
   * @param {string} camelCaseNumber
   * @param {string} singleword
   * @param {string} id
   *
   * @throws {RequiredError}
   */
  getWithQueryParamsRaw: (requestParameters: ApiGetWithQueryParamsRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<any>>;
  /**
   * Test endpoint with various parameter naming conventions
   *
   * @param {NamingConventionTest} body
   *
   * @throws {RequiredError}
   */
  testNamingConventionsRaw: (requestParameters: ApiTestNamingConventionsRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<NamingConventionTest>>;
  /**
   * Get with query parameters
   *
   * @param {string} snakeCaseParam
   * @param {string} snakeCaseNumber
   * @param {string} kebabCaseParam
   * @param {Array<string>} kebabCaseArray
   * @param {string} pascalCaseParam
   * @param {string} pascalCaseNumber
   * @param {string} screamingSnakeCase
   * @param {string} screamingNumber
   * @param {string} camelCaseParam
   * @param {string} camelCaseNumber
   * @param {string} singleword
   * @param {string} id
   *
   * @throws {RequiredError}
   */
  getWithQueryParams: (requestParameters: ApiGetWithQueryParamsRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any>;
  /**
   * Test endpoint with various parameter naming conventions
   *
   * @param {NamingConventionTest} body
   *
   * @throws {RequiredError}
   */
  testNamingConventions: (requestParameters: ApiTestNamingConventionsRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<NamingConventionTest>;
}

export class DefaultApi extends BaseAPI implements DefaultApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * Get with query parameters
   *
   * @param {string} snakeCaseParam
   * @param {string} snakeCaseNumber
   * @param {string} kebabCaseParam
   * @param {Array<string>} kebabCaseArray
   * @param {string} pascalCaseParam
   * @param {string} pascalCaseNumber
   * @param {string} screamingSnakeCase
   * @param {string} screamingNumber
   * @param {string} camelCaseParam
   * @param {string} camelCaseNumber
   * @param {string} singleword
   * @param {string} id
   *
   * @throws {RequiredError}
   */
  async getWithQueryParamsRaw(requestParameters: ApiGetWithQueryParamsRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<any>> {
    if (requestParameters['snakeCaseParam'] == null) {
      throw new RequiredError(
        'snakeCaseParam',
        'Required parameter "snakeCaseParam" was null or undefined when calling getWithQueryParamsRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/test`;
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['snakeCaseParam'] !== undefined) {
      queryParameters['snake_case_param'] = requestParameters['snakeCaseParam'];
    }
    if (requestParameters['snakeCaseNumber'] !== undefined) {
      queryParameters['snake_case_number'] = requestParameters['snakeCaseNumber'];
    }
    if (requestParameters['kebabCaseParam'] !== undefined) {
      queryParameters['kebab-case-param'] = requestParameters['kebabCaseParam'];
    }
    if (requestParameters['kebabCaseArray'] !== undefined) {
      queryParameters['kebab-case-array'] = requestParameters['kebabCaseArray'];
    }
    if (requestParameters['pascalCaseParam'] !== undefined) {
      queryParameters['PascalCaseParam'] = requestParameters['pascalCaseParam'];
    }
    if (requestParameters['pascalCaseNumber'] !== undefined) {
      queryParameters['PascalCaseNumber'] = requestParameters['pascalCaseNumber'];
    }
    if (requestParameters['screamingSnakeCase'] !== undefined) {
      queryParameters['SCREAMING_SNAKE_CASE'] = requestParameters['screamingSnakeCase'];
    }
    if (requestParameters['screamingNumber'] !== undefined) {
      queryParameters['SCREAMING_NUMBER'] = requestParameters['screamingNumber'];
    }
    if (requestParameters['camelCaseParam'] !== undefined) {
      queryParameters['camelCaseParam'] = requestParameters['camelCaseParam'];
    }
    if (requestParameters['camelCaseNumber'] !== undefined) {
      queryParameters['camelCaseNumber'] = requestParameters['camelCaseNumber'];
    }
    if (requestParameters['singleword'] !== undefined) {
      queryParameters['singleword'] = requestParameters['singleword'];
    }
    if (requestParameters['id'] !== undefined) {
      queryParameters['id'] = requestParameters['id'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /**
   * Get with query parameters
   *
   * @param {string} snakeCaseParam
   * @param {string} snakeCaseNumber
   * @param {string} kebabCaseParam
   * @param {Array<string>} kebabCaseArray
   * @param {string} pascalCaseParam
   * @param {string} pascalCaseNumber
   * @param {string} screamingSnakeCase
   * @param {string} screamingNumber
   * @param {string} camelCaseParam
   * @param {string} camelCaseNumber
   * @param {string} singleword
   * @param {string} id
   *
   * @throws {RequiredError}
   */
  async getWithQueryParams(requestParameters: ApiGetWithQueryParamsRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any> {
    const response = await this.getWithQueryParamsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Test endpoint with various parameter naming conventions
   *
   * @param {NamingConventionTest} body
   *
   * @throws {RequiredError}
   */
  async testNamingConventionsRaw(requestParameters: ApiTestNamingConventionsRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<NamingConventionTest>> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling testNamingConventionsRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/test`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = NamingConventionTestToJSON(requestParameters['body']);
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => NamingConventionTestFromJSON(jsonValue));
  }

  /**
   * Test endpoint with various parameter naming conventions
   *
   * @param {NamingConventionTest} body
   *
   * @throws {RequiredError}
   */
  async testNamingConventions(requestParameters: ApiTestNamingConventionsRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<NamingConventionTest> {
    const response = await this.testNamingConventionsRaw(requestParameters, initOverrides);
    return await response.value();
  }
}