/* tslint:disable */
/* eslint-disable */
/**
 * Interface with Enum Reference Test
 *
 * Test case for interfaces that reference enum types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Bar status enum */
export enum BarStatus {
  Foo = "foo",
  Bar = "bar",
  Baz = "baz"
}

export function BarStatusFromJSON(json: any): BarStatus {
  return BarStatusFromJSONTyped(json, false);
}

export function BarStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BarStatus {
  if (json == null) {
    return json;
  }
  return json as BarStatus;
}

export function BarStatusToJSON(value?: BarStatus | null): any {
  return BarStatusToJSONTyped(value, false);
}

export function BarStatusToJSONTyped(value?: BarStatus | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}