/* tslint:disable */
/* eslint-disable */
/**
 * Interface with Enum Reference Test
 *
 * Test case for interfaces that reference enum types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import type { FooType } from './FooType';
import { FooTypeFromJSON, FooTypeToJSON } from './FooType';

export interface FooSpecs {
  fooType: FooType,
}

export function instanceOfFooSpecs(value: object): value is FooSpecs {
  if (!('fooType' in value) || (value as any)['fooType'] === undefined) return false;
  return true;
}

export function FooSpecsFromJSON(json: any): FooSpecs {
  return FooSpecsFromJSONTyped(json, false);
}

export function FooSpecsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooSpecs {
  if (json == null) {
    return json;
  }
  return {
    'fooType': FooTypeFromJSON(json['foo_type']),
  };
}

export function FooSpecsToJSON(value?: FooSpecs | null): any {
  return FooSpecsToJSONTyped(value, false);
}

export function FooSpecsToJSONTyped(value?: FooSpecs | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'foo_type': FooTypeToJSON(value['fooType']),
  };
}

export const FooSpecsPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};