/* tslint:disable */
/* eslint-disable */
/**
 * Interface with Enum Reference Test
 *
 * Test case for interfaces that reference enum types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Foo type enum */
export enum FooType {
  Foo = "foo",
  Bar = "bar",
  Baz = "baz"
}

export function FooTypeFromJSON(json: any): FooType {
  return FooTypeFromJSONTyped(json, false);
}

export function FooTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooType {
  if (json == null) {
    return json;
  }
  return json as FooType;
}

export function FooTypeToJSON(value?: FooType | null): any {
  return FooTypeToJSONTyped(value, false);
}

export function FooTypeToJSONTyped(value?: FooType | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}