/* tslint:disable */
/* eslint-disable */
/**
 * Interface with Enum Reference Test
 *
 * Test case for interfaces that reference enum types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
export * from './Az';
export * from './BarService';
export * from './BarStatus';
export * from './FooSpecs';
export * from './FooType';
export * from './MyJsonData';
