/* tslint:disable */
/* eslint-disable */
/**
 * Intersection Type (allOf) Test
 *
 * Test fixture for allOf intersection types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface Bar {
  id: number,
  name: string,
}

export function instanceOfBar(value: object): value is Bar {
  if (!('id' in value) || (value as any)['id'] === undefined) return false;
  if (!('name' in value) || (value as any)['name'] === undefined) return false;
  return true;
}

export function BarFromJSON(json: any): Bar {
  return BarFromJSONTyped(json, false);
}

export function BarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bar {
  if (json == null) {
    return json;
  }
  return {
    'id': json['id'],
    'name': json['name'],
  };
}

export function BarToJSON(value?: Bar | null): any {
  return BarToJSONTyped(value, false);
}

export function BarToJSONTyped(value?: Bar | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'id': value['id'],
    'name': value['name'],
  };
}

export const BarPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};