/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Boolean type */
export type BooleanType = boolean

export function BooleanTypeFromJSON(json: any): BooleanType {
  return BooleanTypeFromJSONTyped(json, false);
}

export function BooleanTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BooleanType {
  if (json == null) {
    return json;
  }
  return json;
}

export function BooleanTypeToJSON(value?: BooleanType | null): any {
  return BooleanTypeToJSONTyped(value, false);
}

export function BooleanTypeToJSONTyped(value?: BooleanType | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}