/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type ComplexNestedObjectUser, ComplexNestedObjectUserFromJSON, ComplexNestedObjectUserFromJSONTyped, ComplexNestedObjectUserToJSON, instanceOfComplexNestedObjectUser } from './ComplexNestedObjectUser';

export interface ComplexNestedObject {
  id: number,
  user: ComplexNestedObjectUser,
}

export function instanceOfComplexNestedObject(value: unknown): value is ComplexNestedObject {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "id" in value && (value as any)["id"] !== undefined &&
    "user" in value && (value as any)["user"] !== undefined;
  const hasAllTsNames =
    "id" in value && (value as any)["id"] !== undefined &&
    "user" in value && (value as any)["user"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function ComplexNestedObjectFromJSON(json: any): ComplexNestedObject {
  return ComplexNestedObjectFromJSONTyped(json, false);
}

export function ComplexNestedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexNestedObject {
  if (json == null) {
    return json;
  }
  return {
    'id': json['id'],
    'user': ComplexNestedObjectUserFromJSON(json['user']),
  };
}

export function ComplexNestedObjectToJSON(value?: ComplexNestedObject | null): any {
  return ComplexNestedObjectToJSONTyped(value, false);
}

export function ComplexNestedObjectToJSONTyped(value?: ComplexNestedObject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'id': value['id'],
    'user': ComplexNestedObjectUserToJSON(value['user']),
  };
}

export const ComplexNestedObjectPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};