/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type ComplexNestedObjectUserProfile, ComplexNestedObjectUserProfileFromJSON, ComplexNestedObjectUserProfileFromJSONTyped, ComplexNestedObjectUserProfileToJSON, instanceOfComplexNestedObjectUserProfile } from './ComplexNestedObjectUserProfile';

export interface ComplexNestedObjectUser {
  id?: number,
  profile?: ComplexNestedObjectUserProfile,
}

export function instanceOfComplexNestedObjectUser(value: object): value is ComplexNestedObjectUser {
  return true;
}

export function ComplexNestedObjectUserFromJSON(json: any): ComplexNestedObjectUser {
  return ComplexNestedObjectUserFromJSONTyped(json, false);
}

export function ComplexNestedObjectUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexNestedObjectUser {
  if (json == null) {
    return json;
  }
  return {
    'id': json['id'] ?? undefined,
    'profile': ComplexNestedObjectUserProfileFromJSON(json['profile']) ?? undefined,
  };
}

export function ComplexNestedObjectUserToJSON(value?: ComplexNestedObjectUser | null): any {
  return ComplexNestedObjectUserToJSONTyped(value, false);
}

export function ComplexNestedObjectUserToJSONTyped(value?: ComplexNestedObjectUser | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'id': value['id'],
    'profile': ComplexNestedObjectUserProfileToJSON(value['profile']),
  };
}

export const ComplexNestedObjectUserPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};