/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** String with date-time format */
export type DateTimeString = string

export function DateTimeStringFromJSON(json: any): DateTimeString {
  return DateTimeStringFromJSONTyped(json, false);
}

export function DateTimeStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateTimeString {
  if (json == null) {
    return json;
  }
  return json;
}

export function DateTimeStringToJSON(value?: DateTimeString | null): any {
  return DateTimeStringToJSONTyped(value, false);
}

export function DateTimeStringToJSONTyped(value?: DateTimeString | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}