/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Double precision floating point */
export type DoubleType = number

export function DoubleTypeFromJSON(json: any): DoubleType {
  return DoubleTypeFromJSONTyped(json, false);
}

export function DoubleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoubleType {
  if (json == null) {
    return json;
  }
  return json;
}

export function DoubleTypeToJSON(value?: DoubleType | null): any {
  return DoubleTypeToJSONTyped(value, false);
}

export function DoubleTypeToJSONTyped(value?: DoubleType | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}