/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** 32-bit integer */
export type Integer32 = number

export function Integer32FromJSON(json: any): Integer32 {
  return Integer32FromJSONTyped(json, false);
}

export function Integer32FromJSONTyped(json: any, ignoreDiscriminator: boolean): Integer32 {
  if (json == null) {
    return json;
  }
  return json;
}

export function Integer32ToJSON(value?: Integer32 | null): any {
  return Integer32ToJSONTyped(value, false);
}

export function Integer32ToJSONTyped(value?: Integer32 | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}