/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Object with nested object property */
export interface NestedObject {
  metadata?: { created: string },
  user?: { id: number; name: string },
}

export function instanceOfNestedObject(value: object): value is NestedObject {
  return true;
}

export function NestedObjectFromJSON(json: any): NestedObject {
  return NestedObjectFromJSONTyped(json, false);
}

export function NestedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NestedObject {
  if (json == null) {
    return json;
  }
  return {
    'metadata': json['metadata'] ? {
      created: json['metadata']['created'],
    } : undefined,
    'user': json['user'] ? {
      id: json['user']['id'],
      name: json['user']['name'],
    } : undefined,
  };
}

export function NestedObjectToJSON(value?: NestedObject | null): any {
  return NestedObjectToJSONTyped(value, false);
}

export function NestedObjectToJSONTyped(value?: NestedObject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'metadata': value['metadata'] ? {
      'created': value['metadata']['created'],
    } : undefined,
    'user': value['user'] ? {
      'id': value['user']['id'],
      'name': value['user']['name'],
    } : undefined,
  };
}

export const NestedObjectPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};