/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type NestedObjectMetadata, NestedObjectMetadataFromJSON, NestedObjectMetadataFromJSONTyped, NestedObjectMetadataToJSON, instanceOfNestedObjectMetadata } from './NestedObjectMetadata';
import { type NestedObjectUser, NestedObjectUserFromJSON, NestedObjectUserFromJSONTyped, NestedObjectUserToJSON, instanceOfNestedObjectUser } from './NestedObjectUser';

/** Object with nested object property */
export interface NestedObject {
  metadata?: NestedObjectMetadata,
  user?: NestedObjectUser,
}

export function instanceOfNestedObject(value: object): value is NestedObject {
  return true;
}

export function NestedObjectFromJSON(json: any): NestedObject {
  return NestedObjectFromJSONTyped(json, false);
}

export function NestedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NestedObject {
  if (json == null) {
    return json;
  }
  return {
    'metadata': NestedObjectMetadataFromJSON(json['metadata']) ?? undefined,
    'user': NestedObjectUserFromJSON(json['user']) ?? undefined,
  };
}

export function NestedObjectToJSON(value?: NestedObject | null): any {
  return NestedObjectToJSONTyped(value, false);
}

export function NestedObjectToJSONTyped(value?: NestedObject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'metadata': NestedObjectMetadataToJSON(value['metadata']),
    'user': NestedObjectUserToJSON(value['user']),
  };
}

export const NestedObjectPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};