/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Number with minimum value */
export type NumberWithMinimum = number

export function NumberWithMinimumFromJSON(json: any): NumberWithMinimum {
  return NumberWithMinimumFromJSONTyped(json, false);
}

export function NumberWithMinimumFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberWithMinimum {
  if (json == null) {
    return json;
  }
  return json;
}

export function NumberWithMinimumToJSON(value?: NumberWithMinimum | null): any {
  return NumberWithMinimumToJSONTyped(value, false);
}

export function NumberWithMinimumToJSONTyped(value?: NumberWithMinimum | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}