/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** String with maximum length */
export type StringWithMaxLength = string

export function StringWithMaxLengthFromJSON(json: any): StringWithMaxLength {
  return StringWithMaxLengthFromJSONTyped(json, false);
}

export function StringWithMaxLengthFromJSONTyped(json: any, ignoreDiscriminator: boolean): StringWithMaxLength {
  if (json == null) {
    return json;
  }
  return json;
}

export function StringWithMaxLengthToJSON(value?: StringWithMaxLength | null): any {
  return StringWithMaxLengthToJSONTyped(value, false);
}

export function StringWithMaxLengthToJSONTyped(value?: StringWithMaxLength | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}