/* tslint:disable */
/* eslint-disable */
/**
 * Array of Referenced Types Test
 *
 * Test case for array of referenced model types with recursive FromJSON calls
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type User, UserFromJSON, UserFromJSONTyped, UserToJSON, instanceOfUser } from './User';

/** Response containing array of User references */
export interface ResponseListUsers {
  users: Array<User>,
}

export function instanceOfResponseListUsers(value: object): value is ResponseListUsers {
  if (!('users' in value) || (value as any)['users'] === undefined) return false;
  return true;
}

export function ResponseListUsersFromJSON(json: any): ResponseListUsers {
  return ResponseListUsersFromJSONTyped(json, false);
}

export function ResponseListUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseListUsers {
  if (json == null) {
    return json;
  }
  return {
    'users': json['users'].map((item: any) => UserFromJSON(item)),
  };
}

export function ResponseListUsersToJSON(value?: ResponseListUsers | null): any {
  return ResponseListUsersToJSONTyped(value, false);
}

export function ResponseListUsersToJSONTyped(value?: ResponseListUsers | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'users': value['users']?.map((item: any) => UserToJSON(item)),
  };
}

export const ResponseListUsersPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};