/* tslint:disable */
/* eslint-disable */
/**
 * Primitive Array Test
 *
 * Test case for arrays with primitive items (should not be affected by recursive parsing)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Arrays with primitive items should remain unchanged */
export interface PrimitiveArray {
  numberItems: Array<number>,
  stringItems: Array<string>,
}

export function instanceOfPrimitiveArray(value: unknown): value is PrimitiveArray {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "number_items" in value && (value as any)["number_items"] !== undefined &&
    "string_items" in value && (value as any)["string_items"] !== undefined;
  const hasAllTsNames =
    "numberItems" in value && (value as any)["numberItems"] !== undefined &&
    "stringItems" in value && (value as any)["stringItems"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function PrimitiveArrayFromJSON(json: any): PrimitiveArray {
  return PrimitiveArrayFromJSONTyped(json, false);
}

export function PrimitiveArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrimitiveArray {
  if (json == null) {
    return json;
  }
  return {
    'numberItems': json['number_items'],
    'stringItems': json['string_items'],
  };
}

export function PrimitiveArrayToJSON(value?: PrimitiveArray | null): any {
  return PrimitiveArrayToJSONTyped(value, false);
}

export function PrimitiveArrayToJSONTyped(value?: PrimitiveArray | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'number_items': value['numberItems'],
    'string_items': value['stringItems'],
  };
}

export const PrimitiveArrayPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};