/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Nested object in third type */
export interface FooGrault {
  garply: string,
}

export function instanceOfFooGrault(value: unknown): value is FooGrault {
  if (!value || typeof value !== "object") {
    return false;
  }
  return "garply" in value && (value as any)["garply"] !== undefined;
}

export function FooGraultFromJSON(json: any): FooGrault {
  return FooGraultFromJSONTyped(json, false);
}

export function FooGraultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooGrault {
  if (json == null) {
    return json;
  }
  return {
    'garply': json['garply'],
  };
}

export function FooGraultToJSON(value?: FooGrault | null): any {
  return FooGraultToJSONTyped(value, false);
}

export function FooGraultToJSONTyped(value?: FooGrault | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'garply': value['garply'],
  };
}

export const FooGraultPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};