/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Nested object in third type */
export interface FooMember3Grault {
  garply: string,
}

export function instanceOfFooMember3Grault(value: object): value is FooMember3Grault {
  if (!('garply' in value) || (value as any)['garply'] === undefined) return false;
  return true;
}

export function FooMember3GraultFromJSON(json: any): FooMember3Grault {
  return FooMember3GraultFromJSONTyped(json, false);
}

export function FooMember3GraultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooMember3Grault {
  if (json == null) {
    return json;
  }
  return {
    'garply': json['garply'],
  };
}

export function FooMember3GraultToJSON(value?: FooMember3Grault | null): any {
  return FooMember3GraultToJSONTyped(value, false);
}

export function FooMember3GraultToJSONTyped(value?: FooMember3Grault | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'garply': value['garply'],
  };
}

export const FooMember3GraultPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};