/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type FooMember2Quux, FooMember2QuuxFromJSON, FooMember2QuuxFromJSONTyped, FooMember2QuuxToJSON, instanceOfFooMember2Quux } from './FooMember2Quux';

/** Second inline object type */
export interface FooMember2 {
  quux: FooMember2Quux,
}

export function instanceOfFooMember2(value: object): value is FooMember2 {
  if (!('quux' in value) || (value as any)['quux'] === undefined) return false;
  return true;
}

export function FooMember2FromJSON(json: any): FooMember2 {
  return FooMember2FromJSONTyped(json, false);
}

export function FooMember2FromJSONTyped(json: any, ignoreDiscriminator: boolean): FooMember2 {
  if (json == null) {
    return json;
  }
  return {
    'quux': FooMember2QuuxFromJSON(json['quux']),
  };
}

export function FooMember2ToJSON(value?: FooMember2 | null): any {
  return FooMember2ToJSONTyped(value, false);
}

export function FooMember2ToJSONTyped(value?: FooMember2 | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'quux': FooMember2QuuxToJSON(value['quux']),
  };
}

export const FooMember2PropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};