/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Nested object in first type */
export interface FooMember1Bar {
  baz: string,
  qux: string,
}

export function instanceOfFooMember1Bar(value: object): value is FooMember1Bar {
  if (!('baz' in value) || (value as any)['baz'] === undefined) return false;
  if (!('qux' in value) || (value as any)['qux'] === undefined) return false;
  return true;
}

export function FooMember1BarFromJSON(json: any): FooMember1Bar {
  return FooMember1BarFromJSONTyped(json, false);
}

export function FooMember1BarFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooMember1Bar {
  if (json == null) {
    return json;
  }
  return {
    'baz': json['baz'],
    'qux': json['qux'],
  };
}

export function FooMember1BarToJSON(value?: FooMember1Bar | null): any {
  return FooMember1BarToJSONTyped(value, false);
}

export function FooMember1BarToJSONTyped(value?: FooMember1Bar | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'baz': value['baz'],
    'qux': value['qux'],
  };
}

export const FooMember1BarPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};