/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type FooMember1Bar, FooMember1BarFromJSON, FooMember1BarFromJSONTyped, FooMember1BarToJSON, instanceOfFooMember1Bar } from './FooMember1Bar';

/** First inline object type */
export interface FooMember1 {
  bar: FooMember1Bar,
}

export function instanceOfFooMember1(value: object): value is FooMember1 {
  if (!('bar' in value) || (value as any)['bar'] === undefined) return false;
  return true;
}

export function FooMember1FromJSON(json: any): FooMember1 {
  return FooMember1FromJSONTyped(json, false);
}

export function FooMember1FromJSONTyped(json: any, ignoreDiscriminator: boolean): FooMember1 {
  if (json == null) {
    return json;
  }
  return {
    'bar': FooMember1BarFromJSON(json['bar']),
  };
}

export function FooMember1ToJSON(value?: FooMember1 | null): any {
  return FooMember1ToJSONTyped(value, false);
}

export function FooMember1ToJSONTyped(value?: FooMember1 | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'bar': FooMember1BarToJSON(value['bar']),
  };
}

export const FooMember1PropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};