/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Inline Objects Test
 *
 * Test fixture for union types (oneOf) with inline object schemas that should generate named interfaces
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Nested object in second type */
export interface FooMember2Quux {
  corge: string,
}

export function instanceOfFooMember2Quux(value: unknown): value is FooMember2Quux {
  if (!value || typeof value !== "object") {
    return false;
  }
  return "corge" in value && (value as any)["corge"] !== undefined;
}

export function FooMember2QuuxFromJSON(json: any): FooMember2Quux {
  return FooMember2QuuxFromJSONTyped(json, false);
}

export function FooMember2QuuxFromJSONTyped(json: any, ignoreDiscriminator: boolean): FooMember2Quux {
  if (json == null) {
    return json;
  }
  return {
    'corge': json['corge'],
  };
}

export function FooMember2QuuxToJSON(value?: FooMember2Quux | null): any {
  return FooMember2QuuxToJSONTyped(value, false);
}

export function FooMember2QuuxToJSONTyped(value?: FooMember2Quux | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'corge': value['corge'],
  };
}

export const FooMember2QuuxPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};