// Code generated by openapi-nexus. DO NOT EDIT.
// Default And Exact Response API
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

type Widget struct {
	Id string `json:"id"`
	Name string `json:"name"`
}

func (c Widget) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Widget) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"id",
		"name",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *Widget) GetId() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Id
}

func (c *Widget) GetName() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Name
}

