// Code generated by openapi-nexus. DO NOT EDIT.
// No Response Body API
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

type FooRequest struct {
	Bar string `json:"bar"`
}

func (c FooRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *FooRequest) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"bar",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *FooRequest) GetBar() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Bar
}

