/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export type AnyOfTypes = string | number

export function AnyOfTypesFromJSON(json: any): AnyOfTypes {
  return AnyOfTypesFromJSONTyped(json, false);
}

export function AnyOfTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnyOfTypes {
  if (json == null) {
    return json;
  }
  if (typeof json === 'string') {
    return json;
  }
  if (typeof json === 'number') {
    return json;
  }
  if (typeof json !== 'object') {
    return json;
  }
  return {} as any;
}

export function AnyOfTypesToJSON(value?: AnyOfTypes | null): any {
  return AnyOfTypesToJSONTyped(value, false);
}

export function AnyOfTypesToJSONTyped(value?: AnyOfTypes | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'number') {
    return value;
  }
  if (typeof value !== 'object') {
    return value;
  }
  return {};
}