/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export type ArrayWithMaxItems = Array<string>

export function ArrayWithMaxItemsFromJSON(json: any): ArrayWithMaxItems {
  return ArrayWithMaxItemsFromJSONTyped(json, false);
}

export function ArrayWithMaxItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArrayWithMaxItems {
  if (json == null) {
    return json;
  }
  return json;
}

export function ArrayWithMaxItemsToJSON(value?: ArrayWithMaxItems | null): any {
  return ArrayWithMaxItemsToJSONTyped(value, false);
}

export function ArrayWithMaxItemsToJSONTyped(value?: ArrayWithMaxItems | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}