/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** String with binary format */
export type BinaryString = string

export function BinaryStringFromJSON(json: any): BinaryString {
  return BinaryStringFromJSONTyped(json, false);
}

export function BinaryStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryString {
  if (json == null) {
    return json;
  }
  return json;
}

export function BinaryStringToJSON(value?: BinaryString | null): any {
  return BinaryStringToJSONTyped(value, false);
}

export function BinaryStringToJSONTyped(value?: BinaryString | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}