/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** String with email format */
export type EmailString = string

export function EmailStringFromJSON(json: any): EmailString {
  return EmailStringFromJSONTyped(json, false);
}

export function EmailStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailString {
  if (json == null) {
    return json;
  }
  return json;
}

export function EmailStringToJSON(value?: EmailString | null): any {
  return EmailStringToJSONTyped(value, false);
}

export function EmailStringToJSONTyped(value?: EmailString | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}