/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Object without properties */
export type EmptyObject = any

export function EmptyObjectFromJSON(json: any): EmptyObject {
  return EmptyObjectFromJSONTyped(json, false);
}

export function EmptyObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmptyObject {
  if (json == null) {
    return json;
  }
  return json;
}

export function EmptyObjectToJSON(value?: EmptyObject | null): any {
  return EmptyObjectToJSONTyped(value, false);
}

export function EmptyObjectToJSONTyped(value?: EmptyObject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}