/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Floating point number */
export type FloatType = number

export function FloatTypeFromJSON(json: any): FloatType {
  return FloatTypeFromJSONTyped(json, false);
}

export function FloatTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): FloatType {
  if (json == null) {
    return json;
  }
  return json;
}

export function FloatTypeToJSON(value?: FloatType | null): any {
  return FloatTypeToJSONTyped(value, false);
}

export function FloatTypeToJSONTyped(value?: FloatType | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}