/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Basic integer type */
export type IntegerType = number

export function IntegerTypeFromJSON(json: any): IntegerType {
  return IntegerTypeFromJSONTyped(json, false);
}

export function IntegerTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegerType {
  if (json == null) {
    return json;
  }
  return json;
}

export function IntegerTypeToJSON(value?: IntegerType | null): any {
  return IntegerTypeToJSONTyped(value, false);
}

export function IntegerTypeToJSONTyped(value?: IntegerType | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}