/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Number with maximum value */
export type NumberWithMaximum = number

export function NumberWithMaximumFromJSON(json: any): NumberWithMaximum {
  return NumberWithMaximumFromJSONTyped(json, false);
}

export function NumberWithMaximumFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberWithMaximum {
  if (json == null) {
    return json;
  }
  return json;
}

export function NumberWithMaximumToJSON(value?: NumberWithMaximum | null): any {
  return NumberWithMaximumToJSONTyped(value, false);
}

export function NumberWithMaximumToJSONTyped(value?: NumberWithMaximum | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}