/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Basic number type */
export type NumberType = number

export function NumberTypeFromJSON(json: any): NumberType {
  return NumberTypeFromJSONTyped(json, false);
}

export function NumberTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberType {
  if (json == null) {
    return json;
  }
  return json;
}

export function NumberTypeToJSON(value?: NumberType | null): any {
  return NumberTypeToJSONTyped(value, false);
}

export function NumberTypeToJSONTyped(value?: NumberType | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}