/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type BasicObject, BasicObjectFromJSON, BasicObjectFromJSONTyped, BasicObjectToJSON, instanceOfBasicObject } from './BasicObject';
import { type NestedObject, NestedObjectFromJSON, NestedObjectFromJSONTyped, NestedObjectToJSON, instanceOfNestedObject } from './NestedObject';

export type OneOfObjects = BasicObject | NestedObject

export function OneOfObjectsFromJSON(json: any): OneOfObjects {
  return OneOfObjectsFromJSONTyped(json, false);
}

export function OneOfObjectsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneOfObjects {
  if (json == null) {
    return json;
  }
  if (typeof json !== 'object') {
    return json;
  }
  if (instanceOfBasicObject(json)) {
    return BasicObjectFromJSONTyped(json, true);
  }
  if (instanceOfNestedObject(json)) {
    return NestedObjectFromJSONTyped(json, true);
  }
  return {} as any;
}

export function OneOfObjectsToJSON(value?: OneOfObjects | null): any {
  return OneOfObjectsToJSONTyped(value, false);
}

export function OneOfObjectsToJSONTyped(value?: OneOfObjects | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  if (typeof value !== 'object') {
    return value;
  }
  if (instanceOfBasicObject(value)) {
    return BasicObjectToJSON(value as BasicObject);
  }
  if (instanceOfNestedObject(value)) {
    return NestedObjectToJSON(value as NestedObject);
  }
  return {};
}