/* tslint:disable */
/* eslint-disable */
/**
 * Comprehensive Schema Types Example
 *
 * Comprehensive test for all OpenAPI v3.1.2 schema types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** String with UUID format */
export type UuidString = string

export function UuidStringFromJSON(json: any): UuidString {
  return UuidStringFromJSONTyped(json, false);
}

export function UuidStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): UuidString {
  if (json == null) {
    return json;
  }
  return json;
}

export function UuidStringToJSON(value?: UuidString | null): any {
  return UuidStringToJSONTyped(value, false);
}

export function UuidStringToJSONTyped(value?: UuidString | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}