// Code generated by openapi-nexus. DO NOT EDIT.
// Inline Object with Array Test
//
// Test case for inline object containing an array of inline objects
//
// Generated from OpenAPI doc version 1.0.0

package sdk

// TODO: Implement main SDK file
