/* tslint:disable */
/* eslint-disable */
/**
 * Complex Array Structure Test
 *
 * Test case for array of inline objects where each object has nested inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface ComplexArrayStructureNestedData {
  nestedFieldOne?: string,
  nestedFieldTwo?: number,
}

export function instanceOfComplexArrayStructureNestedData(value: object): value is ComplexArrayStructureNestedData {
  return true;
}

export function ComplexArrayStructureNestedDataFromJSON(json: any): ComplexArrayStructureNestedData {
  return ComplexArrayStructureNestedDataFromJSONTyped(json, false);
}

export function ComplexArrayStructureNestedDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexArrayStructureNestedData {
  if (json == null) {
    return json;
  }
  return {
    'nestedFieldOne': json['nested_field_one'] ?? undefined,
    'nestedFieldTwo': json['nested_field_two'] ?? undefined,
  };
}

export function ComplexArrayStructureNestedDataToJSON(value?: ComplexArrayStructureNestedData | null): any {
  return ComplexArrayStructureNestedDataToJSONTyped(value, false);
}

export function ComplexArrayStructureNestedDataToJSONTyped(value?: ComplexArrayStructureNestedData | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'nested_field_one': value['nestedFieldOne'],
    'nested_field_two': value['nestedFieldTwo'],
  };
}

export const ComplexArrayStructureNestedDataPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};