/* tslint:disable */
/* eslint-disable */
/**
 * Complex Array Structure Test
 *
 * Test case for array of inline objects where each object has nested inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
/** Array of inline objects with nested inline objects and arrays */
export interface ComplexArrayStructure {
  items: Array<{ itemId: string; metadata: { createdAt: string; tags: Array<string> }; nestedData: { nestedFieldOne: string; nestedFieldTwo: number } }>,
}

export function instanceOfComplexArrayStructure(value: object): value is ComplexArrayStructure {
  if (!('items' in value) || (value as any)['items'] === undefined) return false;
  return true;
}

export function ComplexArrayStructureFromJSON(json: any): ComplexArrayStructure {
  return ComplexArrayStructureFromJSONTyped(json, false);
}

export function ComplexArrayStructureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplexArrayStructure {
  if (json == null) {
    return json;
  }
  return {
    'items': json['items'].map((item: any) => ({
      itemId: item['item_id'],
      metadata: item['metadata'],
      nestedData: item['nested_data'],
    })),
  };
}

export function ComplexArrayStructureToJSON(value?: ComplexArrayStructure | null): any {
  return ComplexArrayStructureToJSONTyped(value, false);
}

export function ComplexArrayStructureToJSONTyped(value?: ComplexArrayStructure | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'items': value['items']?.map((item: any) => ({
      'item_id': item['itemId'],
      'metadata': item['metadata'],
      'nested_data': item['nestedData'],
    })),
  };
}

export const ComplexArrayStructurePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};