/* tslint:disable */
/* eslint-disable */
/**
 * Nested Union Type Test
 *
 * Test fixture for union types that reference other union types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface Bar {
  endpoint: string,
  type: "bar",
}

export function instanceOfBar(value: object): value is Bar {
  if (!('endpoint' in value) || (value as any)['endpoint'] === undefined) return false;
  if (!('type' in value) || (value as any)['type'] === undefined) return false;
  return true;
}

export function BarFromJSON(json: any): Bar {
  return BarFromJSONTyped(json, false);
}

export function BarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bar {
  if (json == null) {
    return json;
  }
  return {
    'endpoint': json['endpoint'],
    'type': json['type'],
  };
}

export function BarToJSON(value?: Bar | null): any {
  return BarToJSONTyped(value, false);
}

export function BarToJSONTyped(value?: Bar | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'endpoint': value['endpoint'],
    'type': value['type'],
  };
}

export const BarPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};