/* tslint:disable */
/* eslint-disable */
/**
 * Naming Conventions Test
 *
 * Test fixture to verify language property naming conventions
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface NamingConventionTestPascalCaseObject {
  nestedProperty?: string,
}

export function instanceOfNamingConventionTestPascalCaseObject(value: object): value is NamingConventionTestPascalCaseObject {
  return true;
}

export function NamingConventionTestPascalCaseObjectFromJSON(json: any): NamingConventionTestPascalCaseObject {
  return NamingConventionTestPascalCaseObjectFromJSONTyped(json, false);
}

export function NamingConventionTestPascalCaseObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamingConventionTestPascalCaseObject {
  if (json == null) {
    return json;
  }
  return {
    'nestedProperty': json['nested_property'] ?? undefined,
  };
}

export function NamingConventionTestPascalCaseObjectToJSON(value?: NamingConventionTestPascalCaseObject | null): any {
  return NamingConventionTestPascalCaseObjectToJSONTyped(value, false);
}

export function NamingConventionTestPascalCaseObjectToJSONTyped(value?: NamingConventionTestPascalCaseObject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'nested_property': value['nestedProperty'],
  };
}

export const NamingConventionTestPascalCaseObjectPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};