/* tslint:disable */
/* eslint-disable */
/**
 * Naming Conventions Test
 *
 * Test fixture to verify language property naming conventions
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type NamingConventionTestNestedObject, NamingConventionTestNestedObjectFromJSON, NamingConventionTestNestedObjectFromJSONTyped, NamingConventionTestNestedObjectToJSON, instanceOfNamingConventionTestNestedObject } from './NamingConventionTestNestedObject';
import { type NamingConventionTestPascalCaseObject, NamingConventionTestPascalCaseObjectFromJSON, NamingConventionTestPascalCaseObjectFromJSONTyped, NamingConventionTestPascalCaseObjectToJSON, instanceOfNamingConventionTestPascalCaseObject } from './NamingConventionTestPascalCaseObject';

export interface NamingConventionTest {
  pascalCaseField?: string,
  pascalCaseObject?: NamingConventionTestPascalCaseObject,
  screamingNumber?: number,
  screamingSnakeCase?: string,
  camelCaseField: string,
  camelCaseNumber?: number,
  id?: number,
  itemsArray?: Array<{ itemCamelCase: string; itemKebabCase: string; itemPascalCase: string; itemSnakeCase: string }>,
  kebabCaseArray?: Array<string>,
  kebabCaseField?: string,
  nestedObject?: NamingConventionTestNestedObject,
  singleword: string,
  snakeCaseField: string,
  snakeCaseNumber?: number,
}

export function instanceOfNamingConventionTest(value: object): value is NamingConventionTest {
  if (!('camelCaseField' in value) || (value as any)['camelCaseField'] === undefined) return false;
  if (!('singleword' in value) || (value as any)['singleword'] === undefined) return false;
  if (!('snakeCaseField' in value) || (value as any)['snakeCaseField'] === undefined) return false;
  return true;
}

export function NamingConventionTestFromJSON(json: any): NamingConventionTest {
  return NamingConventionTestFromJSONTyped(json, false);
}

export function NamingConventionTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamingConventionTest {
  if (json == null) {
    return json;
  }
  return {
    'pascalCaseField': json['PascalCaseField'] ?? undefined,
    'pascalCaseObject': NamingConventionTestPascalCaseObjectFromJSON(json['PascalCaseObject']) ?? undefined,
    'screamingNumber': json['SCREAMING_NUMBER'] ?? undefined,
    'screamingSnakeCase': json['SCREAMING_SNAKE_CASE'] ?? undefined,
    'camelCaseField': json['camelCaseField'],
    'camelCaseNumber': json['camelCaseNumber'] ?? undefined,
    'id': json['id'] ?? undefined,
    'itemsArray': json['items_array']?.map((item: any) => ({
      itemCamelCase: item['itemCamelCase'],
      itemKebabCase: item['item-kebab-case'],
      itemPascalCase: item['ItemPascalCase'],
      itemSnakeCase: item['item_snake_case'],
    })) ?? undefined,
    'kebabCaseArray': json['kebab-case-array'] ?? undefined,
    'kebabCaseField': json['kebab-case-field'] ?? undefined,
    'nestedObject': NamingConventionTestNestedObjectFromJSON(json['nested_object']) ?? undefined,
    'singleword': json['singleword'],
    'snakeCaseField': json['snake_case_field'],
    'snakeCaseNumber': json['snake_case_number'] ?? undefined,
  };
}

export function NamingConventionTestToJSON(value?: NamingConventionTest | null): any {
  return NamingConventionTestToJSONTyped(value, false);
}

export function NamingConventionTestToJSONTyped(value?: NamingConventionTest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'PascalCaseField': value['pascalCaseField'],
    'PascalCaseObject': NamingConventionTestPascalCaseObjectToJSON(value['pascalCaseObject']),
    'SCREAMING_NUMBER': value['screamingNumber'],
    'SCREAMING_SNAKE_CASE': value['screamingSnakeCase'],
    'camelCaseField': value['camelCaseField'],
    'camelCaseNumber': value['camelCaseNumber'],
    'id': value['id'],
    'items_array': value['itemsArray']?.map((item: any) => ({
      'itemCamelCase': item['itemCamelCase'],
      'item-kebab-case': item['itemKebabCase'],
      'ItemPascalCase': item['itemPascalCase'],
      'item_snake_case': item['itemSnakeCase'],
    })),
    'kebab-case-array': value['kebabCaseArray'],
    'kebab-case-field': value['kebabCaseField'],
    'nested_object': NamingConventionTestNestedObjectToJSON(value['nestedObject']),
    'singleword': value['singleword'],
    'snake_case_field': value['snakeCaseField'],
    'snake_case_number': value['snakeCaseNumber'],
  };
}

export const NamingConventionTestPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};