/* tslint:disable */
/* eslint-disable */
/**
 * Naming Conventions Test
 *
 * Test fixture to verify language property naming conventions
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface NamingConventionTestNestedObject {
  nestedPascalCase?: string,
  nestedKebabCase?: string,
  nestedCamelCase?: string,
  nestedSnakeCase: string,
}

export function instanceOfNamingConventionTestNestedObject(value: object): value is NamingConventionTestNestedObject {
  if (!('nestedSnakeCase' in value) || (value as any)['nestedSnakeCase'] === undefined) return false;
  return true;
}

export function NamingConventionTestNestedObjectFromJSON(json: any): NamingConventionTestNestedObject {
  return NamingConventionTestNestedObjectFromJSONTyped(json, false);
}

export function NamingConventionTestNestedObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): NamingConventionTestNestedObject {
  if (json == null) {
    return json;
  }
  return {
    'nestedPascalCase': json['NestedPascalCase'] ?? undefined,
    'nestedKebabCase': json['nested-kebab-case'] ?? undefined,
    'nestedCamelCase': json['nestedCamelCase'] ?? undefined,
    'nestedSnakeCase': json['nested_snake_case'],
  };
}

export function NamingConventionTestNestedObjectToJSON(value?: NamingConventionTestNestedObject | null): any {
  return NamingConventionTestNestedObjectToJSONTyped(value, false);
}

export function NamingConventionTestNestedObjectToJSONTyped(value?: NamingConventionTestNestedObject | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'NestedPascalCase': value['nestedPascalCase'],
    'nested-kebab-case': value['nestedKebabCase'],
    'nestedCamelCase': value['nestedCamelCase'],
    'nested_snake_case': value['nestedSnakeCase'],
  };
}

export const NamingConventionTestNestedObjectPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};