// Code generated by openapi-nexus. DO NOT EDIT.
// Duplicate Parameter Names Test API
//
// Test API with duplicate parameter names across different locations
//
// Generated from OpenAPI doc version 1.0.0

package config

import (
	"example.com/sdk/retry"
	"net/http"
	"time"
)

type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

type SDKConfiguration struct {
	Client HTTPClient

	ServerURL   string
	UserAgent   string
	RetryConfig *retry.Config
	Timeout     *time.Duration
}

func (c *SDKConfiguration) GetServerDetails() (string, map[string]string) {
	return c.ServerURL, map[string]string{}
}
