// Code generated by openapi-nexus. DO NOT EDIT.
// Array of Referenced Types Test
//
// Test case for array of referenced model types with recursive FromJSON calls
//
// Generated from OpenAPI doc version 1.0.0

package types

func String(s string) *string    { return &s }
func Bool(b bool) *bool          { return &b }
func Int(i int) *int             { return &i }
func Int64(i int64) *int64       { return &i }
func Float32(f float32) *float32 { return &f }
func Float64(f float64) *float64 { return &f }
func Pointer[T any](v T) *T      { return &v }
