//! Rust reqwest code generator: IR → idiomatic Rust + reqwest.
//!
//! Receives a lowered `IrSpec` and emits:
//! 1. Models via `sigil_emit::generate_model_files`.
//! 2. APIs via `sigil_emit_api::generate_api_files`.
//! 3. Hardcoded runtime (`client.rs`, `error.rs`, `auth.rs`).
//! 4. `Cargo.toml`, `lib.rs`, and `README.md`.

use std::error::Error;

use heck::ToKebabCase as _;

use crate::config::RustReqwestConfig;
use crate::runtime::runtime_files;
use crate::{sigil_emit, sigil_emit_api};
use openapi_nexus_core::traits::code_generator::CodeGenerator;
use openapi_nexus_core::traits::file_writer::{FileInfo, FileWriter};
use openapi_nexus_core::{GeneratorType, Language};
use openapi_nexus_ir::types::{IrInfo, IrSpec};

/// Rust reqwest code generator.
#[derive(Debug, Clone)]
pub struct RustReqwestCodeGenerator {
    config: RustReqwestConfig,
}

impl RustReqwestCodeGenerator {
    /// Create a new Rust reqwest generator from a TOML config fragment.
    pub fn new(config: toml::value::Table) -> Self {
        Self {
            config: RustReqwestConfig::from(config),
        }
    }

    fn crate_name(&self, info: &IrInfo) -> String {
        self.config
            .crate_name
            .clone()
            .unwrap_or_else(|| info.title.to_kebab_case())
    }

    fn generate_ir(&self, ir: &IrSpec) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        let header = render_file_header(&ir.info);
        let crate_name = self.crate_name(&ir.info);

        let mut files = Vec::new();

        // Models
        files.extend(
            sigil_emit::generate_model_files(ir, &header).map_err(|msg| {
                Box::<dyn Error + Send + Sync>::from(format!("sigil_emit models: {msg}"))
            })?,
        );

        // APIs
        files.extend(
            sigil_emit_api::generate_api_files(ir, &header).map_err(|msg| {
                Box::<dyn Error + Send + Sync>::from(format!("sigil_emit_api: {msg}"))
            })?,
        );

        // Runtime (hardcoded)
        files.extend(runtime_files(&header));

        // Project files
        files.push(cargo_toml_file(&crate_name, &ir.info));
        files.push(lib_rs_file(&header));
        files.push(readme_file(&ir.info));

        Ok(files)
    }
}

impl CodeGenerator for RustReqwestCodeGenerator {
    fn language(&self) -> Language {
        Language::Rust
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::RustReqwest
    }

    fn generate(&self, ir: &IrSpec) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        self.generate_ir(ir)
    }
}

impl FileWriter for RustReqwestCodeGenerator {}

fn render_file_header(info: &IrInfo) -> String {
    let mut out = String::new();
    out.push_str("// Code generated by openapi-nexus. DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str(&format!("// {} — {}\n", info.title, info.version));
    if let Some(desc) = &info.description {
        for line in desc.lines() {
            out.push_str(&format!("// {line}\n"));
        }
    }
    out.push('\n');
    out
}

fn cargo_toml_file(crate_name: &str, info: &IrInfo) -> FileInfo {
    let description = info.description.as_deref().unwrap_or("Generated Rust SDK.");
    let content = format!(
        r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"
description = "{description}"

[dependencies]
reqwest = {{ version = "0.12", features = ["json"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
tokio = {{ version = "1", features = ["full"] }}
"#,
    );
    FileInfo::project("Cargo.toml".to_string(), content)
}

fn lib_rs_file(header: &str) -> FileInfo {
    let content = format!("{header}pub mod apis;\npub mod models;\npub mod runtime;\n");
    FileInfo::project("lib.rs".to_string(), content)
}

fn readme_file(info: &IrInfo) -> FileInfo {
    let title = &info.title;
    let version = &info.version;
    let description = info
        .description
        .clone()
        .unwrap_or_else(|| "Generated Rust SDK.".to_string());
    let crate_name = info.title.to_kebab_case();
    let content = format!(
        "# {title}\n\n{description}\n\nVersion: `{version}`\n\nGenerated by [openapi-nexus](https://github.com/adamcavendish/openapi-nexus) for `{crate_name}`.\n"
    );
    FileInfo::readme("README.md".to_string(), content)
}
