// Code generated by openapi-nexus. DO NOT EDIT.
// Complex Union Type Test
//
// Test fixture for complex union types
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

type Qux struct {
	Namespace string `json:"namespace"`
	Type string `json:"type"`
	Url string `json:"url"`
}

func (c Qux) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Qux) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"type",
		"url",
		"namespace",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *Qux) GetNamespace() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Namespace
}

func (c *Qux) GetType() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Type
}

func (c *Qux) GetUrl() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Url
}

