/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Any Test
 *
 * Test fixture for union types that include the any type
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export type Config = string | number | any

export function ConfigFromJSON(json: any): Config {
  return ConfigFromJSONTyped(json, false);
}

export function ConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): Config {
  if (json == null) {
    return json;
  }
  return json;
}

export function ConfigToJSON(value?: Config | null): any {
  return ConfigToJSONTyped(value, false);
}

export function ConfigToJSONTyped(value?: Config | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}