// Code generated by openapi-nexus. DO NOT EDIT.
// Comprehensive Schema Types Example
//
// Comprehensive test for all OpenAPI v3.1.2 schema types
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

type ComplexNestedObject struct {
	Id string `json:"id"`
	User string `json:"user"`
}

func (c ComplexNestedObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ComplexNestedObject) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"id",
		"user",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *ComplexNestedObject) GetId() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Id
}

func (c *ComplexNestedObject) GetUser() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.User
}

