// Code generated by openapi-nexus. DO NOT EDIT.
// Comprehensive Schema Types Example
//
// Comprehensive test for all OpenAPI v3.1.2 schema types
//
// Generated from OpenAPI doc version 1.0.0

package components


// String with email format
type EmailString = string
