// Code generated by openapi-nexus. DO NOT EDIT.
// Comprehensive Schema Types Example
//
// Comprehensive test for all OpenAPI v3.1.2 schema types
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// Object with nested object property
type NestedObject struct {
	Metadata optionalnullable.OptionalNullable[string] `json:"metadata,omitzero"`
	User optionalnullable.OptionalNullable[string] `json:"user,omitzero"`
}

func (c NestedObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *NestedObject) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *NestedObject) GetMetadata() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Metadata
}

func (c *NestedObject) GetUser() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.User
}

