// Code generated by openapi-nexus. DO NOT EDIT.
// Comprehensive Schema Types Example
//
// Comprehensive test for all OpenAPI v3.1.2 schema types
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

// Object allowing any additional properties
type ObjectWithAdditionalPropertiesTrue struct {
	Name string `json:"name"`
	AdditionalProperties map[string]interface{} `additionalProperties:"true" json:"-"`
}

func (c ObjectWithAdditionalPropertiesTrue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ObjectWithAdditionalPropertiesTrue) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"name",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *ObjectWithAdditionalPropertiesTrue) GetName() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Name
}

func (c *ObjectWithAdditionalPropertiesTrue) GetAdditionalProperties() map[string]interface{} {
	if c == nil {
		var zero map[string]interface{}
		return zero
	}
	return c.AdditionalProperties
}

