// Code generated by openapi-nexus. DO NOT EDIT.
// Comprehensive Schema Types Example
//
// Comprehensive test for all OpenAPI v3.1.2 schema types
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

// Required enum field in object
type RequiredEnumField struct {
	Status string `json:"status"`
}

func (c RequiredEnumField) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *RequiredEnumField) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"status",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *RequiredEnumField) GetStatus() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Status
}

