//! API client generation for Rust

use utoipa::openapi::OpenApi;

/// API client generator for Rust
pub struct ApiClientGenerator;

impl ApiClientGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate API client code from OpenAPI specification
    pub fn generate_api_client(
        &self,
        _openapi: &OpenApi,
    ) -> Result<String, crate::generator::GeneratorError> {
        // For now, generate a simple placeholder API client
        let code = r#"// DO NOT EDIT - This file is automatically generated.
// Any manual changes will be overwritten on the next generation.
// To make changes, modify the source code and regenerate this file.

use reqwest;
use serde_json;

/// Generated API client for consuming the API
#[derive(Debug, Clone)]
pub struct ApiClient {
    pub base_url: String,
    pub client: reqwest::Client,
}

impl ApiClient {
    /// Create a new API client
    pub fn new(base_url: String) -> Self {
        Self {
            base_url,
            client: reqwest::Client::new(),
        }
    }

    /// Make a GET request
    pub async fn get<T>(&self, path: &str) -> Result<T, reqwest::Error> 
    where
        T: serde::de::DeserializeOwned,
    {
        let url = format!("{}{}", self.base_url, path);
        let response = self.client
            .get(&url)
            .send()
            .await?;
        
        if !response.status().is_success() {
            return Err(reqwest::Error::from(response));
        }
        
        let result: T = response.json().await?;
        Ok(result)
    }

    /// Make a POST request
    pub async fn post<T>(&self, path: &str, body: &serde_json::Value) -> Result<T, reqwest::Error> 
    where
        T: serde::de::DeserializeOwned,
    {
        let url = format!("{}{}", self.base_url, path);
        let response = self.client
            .post(&url)
            .json(body)
            .send()
            .await?;
        
        if !response.status().is_success() {
            return Err(reqwest::Error::from(response));
        }
        
        let result: T = response.json().await?;
        Ok(result)
    }
}"#;

        Ok(code.to_string())
    }
}

impl Default for ApiClientGenerator {
    fn default() -> Self {
        Self::new()
    }
}
