/* tslint:disable */
/* eslint-disable */
/**
 * No Response Body API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
export * from './FooApi';
