// Code generated by openapi-nexus. DO NOT EDIT.
// Optional Nested Object Reference Test
//
// Test case for optional nested object reference
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// User with optional nested profile reference
type UserWithOptionalProfile struct {
	OptionalProfile optionalnullable.OptionalNullable[string] `json:"optional_profile,omitzero"`
	UserId string `json:"user_id"`
}

func (c UserWithOptionalProfile) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *UserWithOptionalProfile) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"user_id",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *UserWithOptionalProfile) GetOptionalProfile() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.OptionalProfile
}

func (c *UserWithOptionalProfile) GetUserId() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.UserId
}

