// Code generated by openapi-nexus. DO NOT EDIT.
// Duplicate Parameter Names Test API
//
// Test API with duplicate parameter names across different locations
//
// Generated from OpenAPI doc version 1.0.0

package utils

import (
	"os"
)

// GetEnv returns the value of the environment variable named by the key or the defaultValue if the environment variable is not set.
func GetEnv(name, defaultValue string) string {
	value := os.Getenv(name)
	if value == "" {
		return defaultValue
	}
	return value
}
