/* tslint:disable */
/* eslint-disable */
/**
 * All Optional Properties Test
 *
 * Test case for object with all optional properties including arrays, references, and inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface AllOptionalPropertiesOptionalInline {
  optionalInlineField?: string,
}

export function instanceOfAllOptionalPropertiesOptionalInline(value: object): value is AllOptionalPropertiesOptionalInline {
  return true;
}

export function AllOptionalPropertiesOptionalInlineFromJSON(json: any): AllOptionalPropertiesOptionalInline {
  return AllOptionalPropertiesOptionalInlineFromJSONTyped(json, false);
}

export function AllOptionalPropertiesOptionalInlineFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllOptionalPropertiesOptionalInline {
  if (json == null) {
    return json;
  }
  return {
    'optionalInlineField': json['optional_inline_field'] ?? undefined,
  };
}

export function AllOptionalPropertiesOptionalInlineToJSON(value?: AllOptionalPropertiesOptionalInline | null): any {
  return AllOptionalPropertiesOptionalInlineToJSONTyped(value, false);
}

export function AllOptionalPropertiesOptionalInlineToJSONTyped(value?: AllOptionalPropertiesOptionalInline | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'optional_inline_field': value['optionalInlineField'],
  };
}

export const AllOptionalPropertiesOptionalInlinePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};