/* tslint:disable */
/* eslint-disable */
/**
 * All Optional Properties Test
 *
 * Test case for object with all optional properties including arrays, references, and inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import type { User } from './User';
import { UserFromJSON, UserToJSON } from './User';

/** Object with all optional properties */
export interface AllOptionalProperties {
  optionalArray?: Array<{ optionalItemField: string }>,
  optionalInline?: { optionalInlineField: string },
  optionalReference?: User,
  optionalString?: string,
}

export function instanceOfAllOptionalProperties(value: object): value is AllOptionalProperties {
  return true;
}

export function AllOptionalPropertiesFromJSON(json: any): AllOptionalProperties {
  return AllOptionalPropertiesFromJSONTyped(json, false);
}

export function AllOptionalPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllOptionalProperties {
  if (json == null) {
    return json;
  }
  return {
    'optionalArray': json['optional_array']?.map((item: any) => ({
      optionalItemField: item['optional_item_field'],
    })) ?? undefined,
    'optionalInline': json['optional_inline'] ? {
      optionalInlineField: json['optional_inline']['optional_inline_field'],
    } : undefined,
    'optionalReference': UserFromJSON(json['optional_reference']) ?? undefined,
    'optionalString': json['optional_string'] ?? undefined,
  };
}

export function AllOptionalPropertiesToJSON(value?: AllOptionalProperties | null): any {
  return AllOptionalPropertiesToJSONTyped(value, false);
}

export function AllOptionalPropertiesToJSONTyped(value?: AllOptionalProperties | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'optional_array': value['optionalArray']?.map((item: any) => ({
      'optional_item_field': item['optionalItemField'],
    })),
    'optional_inline': value['optionalInline'] ? {
      'optional_inline_field': value['optionalInline']['optionalInlineField'],
    } : undefined,
    'optional_reference': UserToJSON(value['optionalReference']),
    'optional_string': value['optionalString'],
  };
}

export const AllOptionalPropertiesPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};