// Code generated by openapi-nexus. DO NOT EDIT.
// Inline Object Test
//
// Test case for inline objects (not arrays) with snake_case to camelCase conversion
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// Object with inline object properties
type InlineObjectTest struct {
	Config optionalnullable.OptionalNullable[string] `json:"config,omitzero"`
	Metadata string `json:"metadata"`
}

func (c InlineObjectTest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *InlineObjectTest) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"metadata",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *InlineObjectTest) GetConfig() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Config
}

func (c *InlineObjectTest) GetMetadata() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Metadata
}

