// Code generated by openapi-nexus. DO NOT EDIT.
// Optional Inline Object Test
//
// Test case for optional inline objects
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// Object with optional inline object property
type OptionalInlineObject struct {
	OptionalConfig optionalnullable.OptionalNullable[string] `json:"optional_config,omitzero"`
}

func (c OptionalInlineObject) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *OptionalInlineObject) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *OptionalInlineObject) GetOptionalConfig() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.OptionalConfig
}

