// Code generated by openapi-nexus. DO NOT EDIT.
// Union Type with Primitives Test
//
// Test fixture for union types with primitive members
//
// Generated from OpenAPI doc version 1.0.0

package components


type Foo = interface{}
