// Code generated by openapi-nexus. DO NOT EDIT.
// Test API with DELETE Response Schema
//
// Test fixture for DELETE operations with JSON response schemas and type alias request bodies
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/internal/utils"
)

// Response after creating a test resource
type CreateTestResourceResponse struct {
	ResourceId string `json:"resource_id"`
}

func (c CreateTestResourceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTestResourceResponse) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"resource_id",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *CreateTestResourceResponse) GetResourceId() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.ResourceId
}

