// Code generated by openapi-nexus. DO NOT EDIT.
// Test API with DELETE Response Schema
//
// Test fixture for DELETE operations with JSON response schemas and type alias request bodies
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// Response after deleting a test resource
type DeleteTestResourceResponse struct {
	Message optionalnullable.OptionalNullable[string] `json:"message,omitzero"`
	Success string `json:"success"`
}

func (c DeleteTestResourceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *DeleteTestResourceResponse) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"success",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *DeleteTestResourceResponse) GetMessage() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Message
}

func (c *DeleteTestResourceResponse) GetSuccess() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Success
}

