// Code generated by openapi-nexus. DO NOT EDIT.
// Test API with DELETE Response Schema
//
// Test fixture for DELETE operations with JSON response schemas and type alias request bodies
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// HTTP error response
type HttpErrorResponse struct {
	Error string `json:"error"`
	Message optionalnullable.OptionalNullable[string] `json:"message,omitzero"`
}

func (c HttpErrorResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *HttpErrorResponse) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"error",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *HttpErrorResponse) GetError() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.Error
}

func (c *HttpErrorResponse) GetMessage() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Message
}

