// Code generated by openapi-nexus. DO NOT EDIT.
// Test API with DELETE Response Schema
//
// Test fixture for DELETE operations with JSON response schemas and type alias request bodies
//
// Generated from OpenAPI doc version 1.0.0

package utils

import (
	"fmt"
	"mime"
	"strings"
)

func MatchContentType(contentType string, pattern string) bool {
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	if contentType == pattern || pattern == "*" || pattern == "*/*" {
		return true
	}

	mediaType, _, err := mime.ParseMediaType(contentType)
	if err != nil {
		return false
	}

	if mediaType == pattern {
		return true
	}

	parts := strings.Split(mediaType, "/")
	if len(parts) == 2 {
		if fmt.Sprintf("%s/*", parts[0]) == pattern || fmt.Sprintf("*/%s", parts[1]) == pattern {
			return true
		}
	}

	return false
}
