/* tslint:disable */
/* eslint-disable */
/**
 * Deeply Nested Inline Objects Test
 *
 * Test case for three levels of nested inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import type { DeeplyNestedInlineLevelOneLevelTwo } from './DeeplyNestedInlineLevelOneLevelTwo';
import { DeeplyNestedInlineLevelOneLevelTwoFromJSON, DeeplyNestedInlineLevelOneLevelTwoToJSON } from './DeeplyNestedInlineLevelOneLevelTwo';

export interface DeeplyNestedInlineLevelOne {
  levelOneField: string,
  levelTwo?: DeeplyNestedInlineLevelOneLevelTwo,
}

export function instanceOfDeeplyNestedInlineLevelOne(value: object): value is DeeplyNestedInlineLevelOne {
  if (!('levelOneField' in value) || (value as any)['levelOneField'] === undefined) return false;
  return true;
}

export function DeeplyNestedInlineLevelOneFromJSON(json: any): DeeplyNestedInlineLevelOne {
  return DeeplyNestedInlineLevelOneFromJSONTyped(json, false);
}

export function DeeplyNestedInlineLevelOneFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeeplyNestedInlineLevelOne {
  if (json == null) {
    return json;
  }
  return {
    'levelOneField': json['level_one_field'],
    'levelTwo': DeeplyNestedInlineLevelOneLevelTwoFromJSON(json['level_two']) ?? undefined,
  };
}

export function DeeplyNestedInlineLevelOneToJSON(value?: DeeplyNestedInlineLevelOne | null): any {
  return DeeplyNestedInlineLevelOneToJSONTyped(value, false);
}

export function DeeplyNestedInlineLevelOneToJSONTyped(value?: DeeplyNestedInlineLevelOne | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'level_one_field': value['levelOneField'],
    'level_two': DeeplyNestedInlineLevelOneLevelTwoToJSON(value['levelTwo']),
  };
}

export const DeeplyNestedInlineLevelOnePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};