/* tslint:disable */
/* eslint-disable */
/**
 * Deeply Nested Inline Objects Test
 *
 * Test case for three levels of nested inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import type { DeeplyNestedInlineLevelOne } from './DeeplyNestedInlineLevelOne';
import { DeeplyNestedInlineLevelOneFromJSON, DeeplyNestedInlineLevelOneToJSON } from './DeeplyNestedInlineLevelOne';

/** Three levels of nested inline objects */
export interface DeeplyNestedInline {
  levelOne: DeeplyNestedInlineLevelOne,
}

export function instanceOfDeeplyNestedInline(value: object): value is DeeplyNestedInline {
  if (!('levelOne' in value) || (value as any)['levelOne'] === undefined) return false;
  return true;
}

export function DeeplyNestedInlineFromJSON(json: any): DeeplyNestedInline {
  return DeeplyNestedInlineFromJSONTyped(json, false);
}

export function DeeplyNestedInlineFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeeplyNestedInline {
  if (json == null) {
    return json;
  }
  return {
    'levelOne': DeeplyNestedInlineLevelOneFromJSON(json['level_one']),
  };
}

export function DeeplyNestedInlineToJSON(value?: DeeplyNestedInline | null): any {
  return DeeplyNestedInlineToJSONTyped(value, false);
}

export function DeeplyNestedInlineToJSONTyped(value?: DeeplyNestedInline | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'level_one': DeeplyNestedInlineLevelOneToJSON(value['levelOne']),
  };
}

export const DeeplyNestedInlinePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};