/* tslint:disable */
/* eslint-disable */
/**
 * Deeply Nested Inline Objects Test
 *
 * Test case for three levels of nested inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type DeeplyNestedInlineLevelOneLevelTwoLevelThree, DeeplyNestedInlineLevelOneLevelTwoLevelThreeFromJSON, DeeplyNestedInlineLevelOneLevelTwoLevelThreeFromJSONTyped, DeeplyNestedInlineLevelOneLevelTwoLevelThreeToJSON, instanceOfDeeplyNestedInlineLevelOneLevelTwoLevelThree } from './DeeplyNestedInlineLevelOneLevelTwoLevelThree';

export interface DeeplyNestedInlineLevelOneLevelTwo {
  levelThree?: DeeplyNestedInlineLevelOneLevelTwoLevelThree,
  levelTwoField?: number,
}

export function instanceOfDeeplyNestedInlineLevelOneLevelTwo(value: unknown): value is DeeplyNestedInlineLevelOneLevelTwo {
  if (!value || typeof value !== "object") {
    return false;
  }
  return true;
}

export function DeeplyNestedInlineLevelOneLevelTwoFromJSON(json: any): DeeplyNestedInlineLevelOneLevelTwo {
  return DeeplyNestedInlineLevelOneLevelTwoFromJSONTyped(json, false);
}

export function DeeplyNestedInlineLevelOneLevelTwoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeeplyNestedInlineLevelOneLevelTwo {
  if (json == null) {
    return json;
  }
  return {
    'levelThree': DeeplyNestedInlineLevelOneLevelTwoLevelThreeFromJSON(json['level_three']) ?? undefined,
    'levelTwoField': json['level_two_field'] ?? undefined,
  };
}

export function DeeplyNestedInlineLevelOneLevelTwoToJSON(value?: DeeplyNestedInlineLevelOneLevelTwo | null): any {
  return DeeplyNestedInlineLevelOneLevelTwoToJSONTyped(value, false);
}

export function DeeplyNestedInlineLevelOneLevelTwoToJSONTyped(value?: DeeplyNestedInlineLevelOneLevelTwo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'level_three': DeeplyNestedInlineLevelOneLevelTwoLevelThreeToJSON(value['levelThree']),
    'level_two_field': value['levelTwoField'],
  };
}

export const DeeplyNestedInlineLevelOneLevelTwoPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};