/* tslint:disable */
/* eslint-disable */
/**
 * Multi Status API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, BlobApiResponse, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, TextApiResponse, VoidApiResponse } from '../runtime/runtime';
import { type ErrorResponse, ErrorResponseFromJSON } from '../models/ErrorResponse';
import { type Widget, WidgetFromJSON } from '../models/Widget';
import { type WidgetListPartial, WidgetListPartialFromJSON } from '../models/WidgetListPartial';

/** API client for Widget operations */

export interface WidgetApiInterface {
  listWidgetsRaw: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Array<Widget>> & { status: 200 } | JSONApiResponse<ErrorResponse> & { status: 404 } | JSONApiResponse<WidgetListPartial> & { status: 206 } | JSONApiResponse<any> & { status: number }>;
  listWidgets: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<Array<Widget> | ErrorResponse | WidgetListPartial>;
}

export class WidgetApi extends BaseAPI implements WidgetApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  async listWidgetsRaw(initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Array<Widget>> & { status: 200 } | JSONApiResponse<ErrorResponse> & { status: 404 } | JSONApiResponse<WidgetListPartial> & { status: 206 } | JSONApiResponse<any> & { status: number }> {
    // Build path with path parameters
    let urlPath = `/widgets`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => (jsonValue as Array<any>).map(WidgetFromJSON)) as JSONApiResponse<Array<Widget>> & { status: 200 };
    }
    else if (response.status === 206) {
      return new JSONApiResponse(response, (jsonValue) => WidgetListPartialFromJSON(jsonValue)) as JSONApiResponse<WidgetListPartial> & { status: 206 };
    }
    else if (response.status === 404) {
      return new JSONApiResponse(response, (jsonValue) => ErrorResponseFromJSON(jsonValue)) as JSONApiResponse<ErrorResponse> & { status: 404 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  async listWidgets(initOverrides?: InitOverrideFunction | RequestInit): Promise<Array<Widget> | ErrorResponse | WidgetListPartial> {
    const response = await this.listWidgetsRaw(initOverrides);
    return await response.value();
  }
}