// Code generated by openapi-nexus. DO NOT EDIT.
// Optional Array of Referenced Types Test
//
// Test case for optional array of referenced model types
//
// Generated from OpenAPI doc version 1.0.0

package sdk

// TODO: Implement main SDK file
