// Code generated by openapi-nexus. DO NOT EDIT.
// Optional Array of Referenced Types Test
//
// Test case for optional array of referenced model types
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// Object with optional array of User references
type OptionalUserList struct {
	OptionalUsers optionalnullable.OptionalNullable[[]User] `json:"optional_users,omitzero"`
}

func (c OptionalUserList) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *OptionalUserList) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *OptionalUserList) GetOptionalUsers() optionalnullable.OptionalNullable[[]User] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[[]User]
		return zero
	}
	return c.OptionalUsers
}

