use std::error::Error;

use heck::ToKebabCase as _;

use super::config::JavaOkhttpConfig;
use super::runtime::runtime_files;
use super::{sigil_emit, sigil_emit_api};
use crate::codegen::traits::code_generator::CodeGenerator;
use crate::codegen::traits::file_writer::{FileInfo, FileWriter};
use crate::codegen::{GeneratorType, Language};
use crate::generators::request_inputs::plan_multipart_request_inputs;
use crate::ir::types::{IrInfo, IrSpec};

const DEFAULT_PACKAGE: &str = "com.example.sdk";

#[derive(Debug, Clone)]
pub struct JavaOkhttpCodeGenerator {
    config: JavaOkhttpConfig,
}

impl JavaOkhttpCodeGenerator {
    pub fn new(config: toml::value::Table) -> Self {
        Self {
            config: JavaOkhttpConfig::from(config),
        }
    }

    fn package_name(&self) -> String {
        self.config
            .package_name
            .clone()
            .unwrap_or_else(|| DEFAULT_PACKAGE.to_string())
    }

    fn generate_ir(&self, ir: &IrSpec) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        let package_name = self.package_name();
        let header = render_file_header(&ir.info);
        let request_inputs = plan_multipart_request_inputs(ir);

        let mut files = Vec::new();

        files.extend(
            sigil_emit::generate_model_files(ir, &package_name, &header, &request_inputs).map_err(
                |msg| Box::<dyn Error + Send + Sync>::from(format!("sigil_emit models: {msg}")),
            )?,
        );

        files.extend(
            sigil_emit_api::generate_api_files(ir, &package_name, &header, &request_inputs)
                .map_err(|msg| {
                    Box::<dyn Error + Send + Sync>::from(format!("sigil_emit_api: {msg}"))
                })?,
        );

        files.extend(runtime_files(
            &header,
            &package_name,
            request_inputs.has_uploads(),
        ));

        files.push(build_gradle_file(&package_name, &ir.info));
        files.push(readme_file(&ir.info));

        Ok(files)
    }
}

impl CodeGenerator for JavaOkhttpCodeGenerator {
    fn language(&self) -> Language {
        Language::Java
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::JavaOkhttp
    }

    fn generate(&self, ir: &IrSpec) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        self.generate_ir(ir)
    }
}

impl FileWriter for JavaOkhttpCodeGenerator {}

fn render_file_header(info: &IrInfo) -> String {
    let mut out = String::new();
    out.push_str("// Code generated by openapi-nexus. DO NOT EDIT.\n");
    out.push_str("//\n");
    out.push_str(&format!("// {} — {}\n", info.title, info.version));
    if let Some(desc) = &info.description {
        for line in desc.lines() {
            out.push_str(&format!("// {line}\n"));
        }
    }
    out.push('\n');
    out
}

fn build_gradle_file(package_name: &str, info: &IrInfo) -> FileInfo {
    let content = format!(
        r#"plugins {{
    id("java-library")
}}

group = "{package_name}"
version = "{version}"

repositories {{
    mavenCentral()
}}

dependencies {{
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.google.code.gson:gson:2.11.0")
}}

java {{
    toolchain {{
        languageVersion.set(JavaLanguageVersion.of(17))
    }}
}}
"#,
        version = info.version,
    );
    FileInfo::project("build.gradle".to_string(), content)
}

fn readme_file(info: &IrInfo) -> FileInfo {
    let title = &info.title;
    let version = &info.version;
    let description = info
        .description
        .clone()
        .unwrap_or_else(|| "Generated Java SDK.".to_string());
    let package = info.title.to_kebab_case();
    let content = format!(
        "# {title}\n\n{description}\n\nVersion: `{version}`\n\nGenerated by [openapi-nexus](https://github.com/adamcavendish/openapi-nexus) for `{package}`.\n"
    );
    FileInfo::readme("README.md".to_string(), content)
}
