/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Mixed Members Test
 *
 * Test fixture for union types with both interfaces and primitives
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, VoidApiResponse } from '../runtime/runtime';
import { type Foo, FooFromJSON } from '../models/Foo';

export interface ApiTestMixedUnionRequest {
    body: Foo;
}

/** API client for default operations */

export interface DefaultApiInterface {
  /**
   * Test endpoint with mixed union type
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  testMixedUnionRaw: (requestParameters: ApiTestMixedUnionRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Foo>>;
  /**
   * Test endpoint with mixed union type
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  testMixedUnion: (requestParameters: ApiTestMixedUnionRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<Foo>;
}

export class DefaultApi extends BaseAPI implements DefaultApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * Test endpoint with mixed union type
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  async testMixedUnionRaw(requestParameters: ApiTestMixedUnionRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Foo>> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling testMixedUnionRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/test`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = requestParameters['body'];
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => FooFromJSON(jsonValue));
  }

  /**
   * Test endpoint with mixed union type
   *
   * @param {Foo} body
   *
   * @throws {RequiredError}
   */
  async testMixedUnion(requestParameters: ApiTestMixedUnionRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<Foo> {
    const response = await this.testMixedUnionRaw(requestParameters, initOverrides);
    return await response.value();
  }
}