/* tslint:disable */
/* eslint-disable */
/**
 * Multi Status API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type Widget, WidgetFromJSON, WidgetFromJSONTyped, WidgetToJSON, instanceOfWidget } from './Widget';

export interface WidgetListPartial {
  hasMore?: boolean,
  items: Array<Widget>,
}

export function instanceOfWidgetListPartial(value: unknown): value is WidgetListPartial {
  if (!value || typeof value !== "object") {
    return false;
  }
  return "items" in value && (value as any)["items"] !== undefined;
}

export function WidgetListPartialFromJSON(json: any): WidgetListPartial {
  return WidgetListPartialFromJSONTyped(json, false);
}

export function WidgetListPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): WidgetListPartial {
  if (json == null) {
    return json;
  }
  return {
    'hasMore': json['hasMore'] ?? undefined,
    'items': json['items'].map((item: any) => WidgetFromJSON(item)),
  };
}

export function WidgetListPartialToJSON(value?: WidgetListPartial | null): any {
  return WidgetListPartialToJSONTyped(value, false);
}

export function WidgetListPartialToJSONTyped(value?: WidgetListPartial | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'hasMore': value['hasMore'],
    'items': value['items']?.map((item: any) => WidgetToJSON(item)),
  };
}

export const WidgetListPartialPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};