/* tslint:disable */
/* eslint-disable */
/**
 * Test API with DELETE Response Schema
 *
 * Test fixture for DELETE operations with JSON response schemas and type alias request bodies
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Response after creating a test resource */
export interface CreateTestResourceResponse {
  resourceId: string,
}

export function instanceOfCreateTestResourceResponse(value: unknown): value is CreateTestResourceResponse {
  if (!value || typeof value !== "object") {
    return false;
  }
  return "resource_id" in value && (value as any)["resource_id"] !== undefined;
}

export function CreateTestResourceResponseFromJSON(json: any): CreateTestResourceResponse {
  return CreateTestResourceResponseFromJSONTyped(json, false);
}

export function CreateTestResourceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTestResourceResponse {
  if (json == null) {
    return json;
  }
  return {
    'resourceId': json['resource_id'],
  };
}

export function CreateTestResourceResponseToJSON(value?: CreateTestResourceResponse | null): any {
  return CreateTestResourceResponseToJSONTyped(value, false);
}

export function CreateTestResourceResponseToJSONTyped(value?: CreateTestResourceResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'resource_id': value['resourceId'],
  };
}

export const CreateTestResourceResponsePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};