/* tslint:disable */
/* eslint-disable */
/**
 * Test API with DELETE Response Schema
 *
 * Test fixture for DELETE operations with JSON response schemas and type alias request bodies
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** Response after deleting a test resource */
export interface DeleteTestResourceResponse {
  message?: string,
  success: boolean,
}

export function instanceOfDeleteTestResourceResponse(value: object): value is DeleteTestResourceResponse {
  if (!('success' in value) || (value as any)['success'] === undefined) return false;
  return true;
}

export function DeleteTestResourceResponseFromJSON(json: any): DeleteTestResourceResponse {
  return DeleteTestResourceResponseFromJSONTyped(json, false);
}

export function DeleteTestResourceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTestResourceResponse {
  if (json == null) {
    return json;
  }
  return {
    'message': json['message'] ?? undefined,
    'success': json['success'],
  };
}

export function DeleteTestResourceResponseToJSON(value?: DeleteTestResourceResponse | null): any {
  return DeleteTestResourceResponseToJSONTyped(value, false);
}

export function DeleteTestResourceResponseToJSONTyped(value?: DeleteTestResourceResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'message': value['message'],
    'success': value['success'],
  };
}

export const DeleteTestResourceResponsePropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};