// Code generated by openapi-nexus. DO NOT EDIT.
// All Optional Properties Test
//
// Test case for object with all optional properties including arrays, references, and inline objects
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// User model with snake_case properties
type User struct {
	EmailAddress optionalnullable.OptionalNullable[string] `json:"email_address,omitzero"`
	UserId string `json:"user_id"`
	UserName string `json:"user_name"`
}

func (c User) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *User) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
		"user_id",
		"user_name",
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *User) GetEmailAddress() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.EmailAddress
}

func (c *User) GetUserId() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.UserId
}

func (c *User) GetUserName() string {
	if c == nil {
		var zero string
		return zero
	}
	return c.UserName
}

