//! Python httpx code generator: IR → idiomatic Python + httpx (synchronous).

use std::error::Error;
use std::sync::OnceLock;

use heck::ToKebabCase as _;

use crate::config::PythonHttpxConfig;
use crate::runtime::runtime_files;
use crate::{emit_api, emit_models, project_files};
use openapi_nexus_core::traits::code_generator::CodeGenerator;
use openapi_nexus_core::traits::file_writer::{FileInfo, FileWriter};
use openapi_nexus_core::{GeneratorType, Language};
use openapi_nexus_ir::types::{IrInfo, IrSpec};

/// Python httpx code generator (synchronous).
#[derive(Debug)]
pub struct PythonHttpxCodeGenerator {
    config: PythonHttpxConfig,
    resolved_package_name: OnceLock<String>,
}

impl Clone for PythonHttpxCodeGenerator {
    fn clone(&self) -> Self {
        Self {
            config: self.config.clone(),
            resolved_package_name: OnceLock::new(),
        }
    }
}

impl PythonHttpxCodeGenerator {
    pub fn new(config: toml::value::Table) -> Self {
        Self {
            config: PythonHttpxConfig::from(config),
            resolved_package_name: OnceLock::new(),
        }
    }

    fn package_name(&self, info: &IrInfo) -> String {
        self.config
            .package_name
            .clone()
            .unwrap_or_else(|| info.title.to_kebab_case().replace('-', "_"))
    }

    fn generate_ir(&self, ir: &IrSpec) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        let package_name = self.package_name(&ir.info);
        let _ = self.resolved_package_name.set(package_name.clone());
        let header = render_file_header(&ir.info);

        let mut files = Vec::new();

        files.extend(
            emit_models::generate_model_files(ir, &header).map_err(|msg| {
                Box::<dyn Error + Send + Sync>::from(format!("emit_models: {msg}"))
            })?,
        );

        files.extend(
            emit_api::generate_api_files(ir, &header)
                .map_err(|msg| Box::<dyn Error + Send + Sync>::from(format!("emit_api: {msg}")))?,
        );

        files.extend(runtime_files(&header));

        files.extend(project_files::generate_project_files(
            &ir.info,
            &package_name,
            &header,
            &ir.schemas,
            &ir.operations,
        ));

        Ok(files)
    }
}

impl CodeGenerator for PythonHttpxCodeGenerator {
    fn language(&self) -> Language {
        Language::Python
    }

    fn generator_type(&self) -> GeneratorType {
        GeneratorType::PythonHttpx
    }

    fn generate(&self, ir: &IrSpec) -> Result<Vec<FileInfo>, Box<dyn Error + Send + Sync>> {
        self.generate_ir(ir)
    }
}

impl FileWriter for PythonHttpxCodeGenerator {
    fn source_dir(&self) -> Option<&str> {
        self.resolved_package_name.get().map(|s| s.as_str())
    }
}

fn render_file_header(info: &IrInfo) -> String {
    let mut out = String::new();
    out.push_str("# Code generated by openapi-nexus. DO NOT EDIT.\n");
    out.push_str("#\n");
    out.push_str(&format!("# {} — {}\n", info.title, info.version));
    if let Some(desc) = &info.description {
        for line in desc.lines() {
            out.push_str(&format!("# {line}\n"));
        }
    }
    out.push('\n');
    out
}
