/* tslint:disable */
/* eslint-disable */
/**
 * Mixed Property Types Test
 *
 * Test case for object with mix of simple types, arrays, references, and inline objects
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type MixedPropertyTypesInlineObject, MixedPropertyTypesInlineObjectFromJSON, MixedPropertyTypesInlineObjectFromJSONTyped, MixedPropertyTypesInlineObjectToJSON, instanceOfMixedPropertyTypesInlineObject } from './MixedPropertyTypesInlineObject';
import { type User, UserFromJSON, UserFromJSONTyped, UserToJSON, instanceOfUser } from './User';

/** Object with mixed property types */
export interface MixedPropertyTypes {
  arrayOfInline: Array<{ inlineField: string }>,
  inlineObject?: MixedPropertyTypesInlineObject,
  nestedReference?: User,
  simpleNumber?: number,
  simpleString: string,
}

export function instanceOfMixedPropertyTypes(value: unknown): value is MixedPropertyTypes {
  if (!value || typeof value !== "object") {
    return false;
  }
  return "array_of_inline" in value && (value as any)["array_of_inline"] !== undefined && "simple_string" in value && (value as any)["simple_string"] !== undefined;
}

export function MixedPropertyTypesFromJSON(json: any): MixedPropertyTypes {
  return MixedPropertyTypesFromJSONTyped(json, false);
}

export function MixedPropertyTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MixedPropertyTypes {
  if (json == null) {
    return json;
  }
  return {
    'arrayOfInline': json['array_of_inline'].map((item: any) => ({
      inlineField: item['inline_field'],
    })),
    'inlineObject': MixedPropertyTypesInlineObjectFromJSON(json['inline_object']) ?? undefined,
    'nestedReference': UserFromJSON(json['nested_reference']) ?? undefined,
    'simpleNumber': json['simple_number'] ?? undefined,
    'simpleString': json['simple_string'],
  };
}

export function MixedPropertyTypesToJSON(value?: MixedPropertyTypes | null): any {
  return MixedPropertyTypesToJSONTyped(value, false);
}

export function MixedPropertyTypesToJSONTyped(value?: MixedPropertyTypes | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'array_of_inline': value['arrayOfInline']?.map((item: any) => ({
      'inline_field': item['inlineField'],
    })),
    'inline_object': MixedPropertyTypesInlineObjectToJSON(value['inlineObject']),
    'nested_reference': UserToJSON(value['nestedReference']),
    'simple_number': value['simpleNumber'],
    'simple_string': value['simpleString'],
  };
}

export const MixedPropertyTypesPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};