/* tslint:disable */
/* eslint-disable */
/**
 * Simple Type Alias Test
 *
 * Test fixture for simple type aliases (not unions or intersections)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** A simple number type alias */
export type Bar = number

export function BarFromJSON(json: any): Bar {
  return BarFromJSONTyped(json, false);
}

export function BarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bar {
  if (json == null) {
    return json;
  }
  return json;
}

export function BarToJSON(value?: Bar | null): any {
  return BarToJSONTyped(value, false);
}

export function BarToJSONTyped(value?: Bar | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}