/* tslint:disable */
/* eslint-disable */
/**
 * Simple Type Alias Test
 *
 * Test fixture for simple type aliases (not unions or intersections)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

/** A simple string type alias */
export type Foo = string

export function FooFromJSON(json: any): Foo {
  return FooFromJSONTyped(json, false);
}

export function FooFromJSONTyped(json: any, ignoreDiscriminator: boolean): Foo {
  if (json == null) {
    return json;
  }
  return json;
}

export function FooToJSON(value?: Foo | null): any {
  return FooToJSONTyped(value, false);
}

export function FooToJSONTyped(value?: Foo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}