/* tslint:disable */
/* eslint-disable */
/**
 * Petstore API
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, BlobApiResponse, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, TextApiResponse, VoidApiResponse } from '../runtime/runtime';
import { type Pet, PetFromJSON, PetToJSON } from '../models/Pet';
import { type UploadResponse, UploadResponseFromJSON } from '../models/UploadResponse';

export interface ApiAddPetRequest {
    body: Pet;
}

export interface ApiDeletePetRequest {
    petId: string;
}

export interface ApiFindPetsByStatusRequest {
    status: string;
}

export interface ApiFindPetsByTagsRequest {
    tags: Array<string>;
}

export interface ApiGetPetByIdRequest {
    petId: string;
}

export interface ApiUpdatePetRequest {
    body: Pet;
}

export interface ApiUpdatePetWithFormRequest {
    petId: string;
    name?: string;
    status?: string;
}

export interface ApiUploadFileRequest {
    petId: string;
    additionalMetadata?: string;
}

/** API client for pet operations */

export interface PetApiInterface {
  /**
   * Add a new pet to the store
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  addPetRaw: (requestParameters: ApiAddPetRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: 422 }>;
  /**
   * Update an existing pet
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  updatePetRaw: (requestParameters: ApiUpdatePetRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: 404 } | VoidApiResponse & { status: 422 }>;
  /**
   * Find pets by status
   *
   * @param {string} status Status values that need to be considered for filter
   *
   * @throws {RequiredError}
   */
  findPetsByStatusRaw: (requestParameters: ApiFindPetsByStatusRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Array<Pet>> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 }>;
  /**
   * Find pets by tags
   *
   * @param {Array<string>} tags Tags to filter by
   *
   * @throws {RequiredError}
   */
  findPetsByTagsRaw: (requestParameters: ApiFindPetsByTagsRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Array<Pet>> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 }>;
  /**
   * Find pet by ID
   *
   * @param {string} petId ID of pet to return
   *
   * @throws {RequiredError}
   */
  getPetByIdRaw: (requestParameters: ApiGetPetByIdRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: 404 }>;
  /**
   * Update a pet in the store with form data
   *
   * @param {string} petId ID of pet that needs to be updated
   * @param {string} name Name of pet that needs to be updated
   * @param {string} status Status of pet that needs to be updated
   *
   * @throws {RequiredError}
   */
  updatePetWithFormRaw: (requestParameters: ApiUpdatePetWithFormRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 }>;
  /**
   * Delete a pet
   *
   * @param {string} petId Pet id to delete
   *
   * @throws {RequiredError}
   */
  deletePetRaw: (requestParameters: ApiDeletePetRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<VoidApiResponse & { status: 200 } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: number }>;
  /**
   * Upload an image
   *
   * @param {string} petId ID of pet to update
   * @param {string} additionalMetadata Additional Metadata
   *
   * @throws {RequiredError}
   */
  uploadFileRaw: (requestParameters: ApiUploadFileRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<UploadResponse> & { status: 200 } | JSONApiResponse<any> & { status: number }>;
  /**
   * Add a new pet to the store
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  addPet: (requestParameters: ApiAddPetRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any | Pet>;
  /**
   * Delete a pet
   *
   * @param {string} petId Pet id to delete
   *
   * @throws {RequiredError}
   */
  deletePet: (requestParameters: ApiDeletePetRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any | void>;
  /**
   * Find pets by status
   *
   * @param {string} status Status values that need to be considered for filter
   *
   * @throws {RequiredError}
   */
  findPetsByStatus: (requestParameters: ApiFindPetsByStatusRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any | Array<Pet>>;
  /**
   * Find pets by tags
   *
   * @param {Array<string>} tags Tags to filter by
   *
   * @throws {RequiredError}
   */
  findPetsByTags: (requestParameters: ApiFindPetsByTagsRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any | Array<Pet>>;
  /**
   * Find pet by ID
   *
   * @param {string} petId ID of pet to return
   *
   * @throws {RequiredError}
   */
  getPetById: (requestParameters: ApiGetPetByIdRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any | Pet>;
  /**
   * Update an existing pet
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  updatePet: (requestParameters: ApiUpdatePetRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any | Pet>;
  /**
   * Update a pet in the store with form data
   *
   * @param {string} petId ID of pet that needs to be updated
   * @param {string} name Name of pet that needs to be updated
   * @param {string} status Status of pet that needs to be updated
   *
   * @throws {RequiredError}
   */
  updatePetWithForm: (requestParameters: ApiUpdatePetWithFormRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any | Pet>;
  /**
   * Upload an image
   *
   * @param {string} petId ID of pet to update
   * @param {string} additionalMetadata Additional Metadata
   *
   * @throws {RequiredError}
   */
  uploadFile: (requestParameters: ApiUploadFileRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<UploadResponse>;
}

export class PetApi extends BaseAPI implements PetApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * Add a new pet to the store
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  async addPetRaw(requestParameters: ApiAddPetRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: 422 }> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling addPetRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = PetToJSON(requestParameters['body']);
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => PetFromJSON(jsonValue)) as JSONApiResponse<Pet> & { status: 200 };
    }
    else if (response.status === 400) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 400 };
    }
    else if (response.status === 422) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 422 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Add a new pet to the store
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  async addPet(requestParameters: ApiAddPetRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any | Pet> {
    const response = await this.addPetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update an existing pet
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  async updatePetRaw(requestParameters: ApiUpdatePetRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: 404 } | VoidApiResponse & { status: 422 }> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling updatePetRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = PetToJSON(requestParameters['body']);
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => PetFromJSON(jsonValue)) as JSONApiResponse<Pet> & { status: 200 };
    }
    else if (response.status === 400) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 400 };
    }
    else if (response.status === 404) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 404 };
    }
    else if (response.status === 422) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 422 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Update an existing pet
   *
   * @param {Pet} body
   *
   * @throws {RequiredError}
   */
  async updatePet(requestParameters: ApiUpdatePetRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any | Pet> {
    const response = await this.updatePetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Find pets by status
   *
   * @param {string} status Status values that need to be considered for filter
   *
   * @throws {RequiredError}
   */
  async findPetsByStatusRaw(requestParameters: ApiFindPetsByStatusRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Array<Pet>> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 }> {
    if (requestParameters['status'] == null) {
      throw new RequiredError(
        'status',
        'Required parameter "status" was null or undefined when calling findPetsByStatusRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet/findByStatus`;
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['status'] !== undefined) {
      queryParameters['status'] = requestParameters['status'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => (jsonValue as Array<any>).map(PetFromJSON)) as JSONApiResponse<Array<Pet>> & { status: 200 };
    }
    else if (response.status === 400) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 400 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Find pets by status
   *
   * @param {string} status Status values that need to be considered for filter
   *
   * @throws {RequiredError}
   */
  async findPetsByStatus(requestParameters: ApiFindPetsByStatusRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any | Array<Pet>> {
    const response = await this.findPetsByStatusRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Find pets by tags
   *
   * @param {Array<string>} tags Tags to filter by
   *
   * @throws {RequiredError}
   */
  async findPetsByTagsRaw(requestParameters: ApiFindPetsByTagsRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Array<Pet>> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 }> {
    if (requestParameters['tags'] == null) {
      throw new RequiredError(
        'tags',
        'Required parameter "tags" was null or undefined when calling findPetsByTagsRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet/findByTags`;
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['tags'] !== undefined) {
      queryParameters['tags'] = requestParameters['tags'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => (jsonValue as Array<any>).map(PetFromJSON)) as JSONApiResponse<Array<Pet>> & { status: 200 };
    }
    else if (response.status === 400) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 400 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Find pets by tags
   *
   * @param {Array<string>} tags Tags to filter by
   *
   * @throws {RequiredError}
   */
  async findPetsByTags(requestParameters: ApiFindPetsByTagsRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any | Array<Pet>> {
    const response = await this.findPetsByTagsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Find pet by ID
   *
   * @param {string} petId ID of pet to return
   *
   * @throws {RequiredError}
   */
  async getPetByIdRaw(requestParameters: ApiGetPetByIdRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: 404 }> {
    if (requestParameters['petId'] == null) {
      throw new RequiredError(
        'petId',
        'Required parameter "petId" was null or undefined when calling getPetByIdRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet/{petId}`;
    urlPath = urlPath.replace(`{${ 'petId' }}`, encodeURIComponent(String(requestParameters['petId'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => PetFromJSON(jsonValue)) as JSONApiResponse<Pet> & { status: 200 };
    }
    else if (response.status === 400) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 400 };
    }
    else if (response.status === 404) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 404 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Find pet by ID
   *
   * @param {string} petId ID of pet to return
   *
   * @throws {RequiredError}
   */
  async getPetById(requestParameters: ApiGetPetByIdRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any | Pet> {
    const response = await this.getPetByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update a pet in the store with form data
   *
   * @param {string} petId ID of pet that needs to be updated
   * @param {string} name Name of pet that needs to be updated
   * @param {string} status Status of pet that needs to be updated
   *
   * @throws {RequiredError}
   */
  async updatePetWithFormRaw(requestParameters: ApiUpdatePetWithFormRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Pet> & { status: 200 } | JSONApiResponse<any> & { status: number } | VoidApiResponse & { status: 400 }> {
    if (requestParameters['petId'] == null) {
      throw new RequiredError(
        'petId',
        'Required parameter "petId" was null or undefined when calling updatePetWithFormRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet/{petId}`;
    urlPath = urlPath.replace(`{${ 'petId' }}`, encodeURIComponent(String(requestParameters['petId'])));
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['name'] !== undefined) {
      queryParameters['name'] = requestParameters['name'];
    }
    if (requestParameters['status'] !== undefined) {
      queryParameters['status'] = requestParameters['status'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => PetFromJSON(jsonValue)) as JSONApiResponse<Pet> & { status: 200 };
    }
    else if (response.status === 400) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 400 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Update a pet in the store with form data
   *
   * @param {string} petId ID of pet that needs to be updated
   * @param {string} name Name of pet that needs to be updated
   * @param {string} status Status of pet that needs to be updated
   *
   * @throws {RequiredError}
   */
  async updatePetWithForm(requestParameters: ApiUpdatePetWithFormRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any | Pet> {
    const response = await this.updatePetWithFormRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete a pet
   *
   * @param {string} petId Pet id to delete
   *
   * @throws {RequiredError}
   */
  async deletePetRaw(requestParameters: ApiDeletePetRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<VoidApiResponse & { status: 200 } | VoidApiResponse & { status: 400 } | VoidApiResponse & { status: number }> {
    if (requestParameters['petId'] == null) {
      throw new RequiredError(
        'petId',
        'Required parameter "petId" was null or undefined when calling deletePetRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet/{petId}`;
    urlPath = urlPath.replace(`{${ 'petId' }}`, encodeURIComponent(String(requestParameters['petId'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 200 };
    }
    else if (response.status === 400) {
      return new VoidApiResponse(response) as VoidApiResponse & { status: 400 };
    }
    else {
      return new VoidApiResponse(response) as VoidApiResponse & { status: number };
    }

  }

  /**
   * Delete a pet
   *
   * @param {string} petId Pet id to delete
   *
   * @throws {RequiredError}
   */
  async deletePet(requestParameters: ApiDeletePetRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any | void> {
    const response = await this.deletePetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Upload an image
   *
   * @param {string} petId ID of pet to update
   * @param {string} additionalMetadata Additional Metadata
   *
   * @throws {RequiredError}
   */
  async uploadFileRaw(requestParameters: ApiUploadFileRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<UploadResponse> & { status: 200 } | JSONApiResponse<any> & { status: number }> {
    if (requestParameters['petId'] == null) {
      throw new RequiredError(
        'petId',
        'Required parameter "petId" was null or undefined when calling uploadFileRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/pet/{petId}/uploadImage`;
    urlPath = urlPath.replace(`{${ 'petId' }}`, encodeURIComponent(String(requestParameters['petId'])));
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['additionalMetadata'] !== undefined) {
      queryParameters['additionalMetadata'] = requestParameters['additionalMetadata'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);

    // Handle responses
    if (response.status === 200) {
      return new JSONApiResponse(response, (jsonValue) => UploadResponseFromJSON(jsonValue)) as JSONApiResponse<UploadResponse> & { status: 200 };
    }
    else {
      return new JSONApiResponse(response) as JSONApiResponse<any> & { status: number };
    }

  }

  /**
   * Upload an image
   *
   * @param {string} petId ID of pet to update
   * @param {string} additionalMetadata Additional Metadata
   *
   * @throws {RequiredError}
   */
  async uploadFile(requestParameters: ApiUploadFileRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<UploadResponse> {
    const response = await this.uploadFileRaw(requestParameters, initOverrides);
    return await response.value();
  }
}