/* tslint:disable */
/* eslint-disable */
/**
 * Petstore API
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, JSONApiResponse, VoidApiResponse, ResponseError, RequiredError, type Configuration, type InitOverrideFunction } from '../runtime/runtime';
import type { Order } from '../models/Order';
import { OrderFromJSON, OrderToJSON } from '../models/Order';

export interface ApiDeleteOrderRequest {
    orderId: string;
}

export interface ApiGetOrderByIdRequest {
    orderId: string;
}

export interface ApiPlaceOrderRequest {
    body: Order;
}

/** API client for store operations */

export interface StoreApiInterface {
  /** Returns pet inventories by status */
  getInventoryRaw: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<string>>;
  /**
   * Place an order for a pet
   *
   * @param {Order} body
   *
   * @throws {RequiredError}
   */
  placeOrderRaw: (requestParameters: ApiPlaceOrderRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Order>>;
  /**
   * Find purchase order by ID
   *
   * @param {string} orderId ID of order that needs to be fetched
   *
   * @throws {RequiredError}
   */
  getOrderByIdRaw: (requestParameters: ApiGetOrderByIdRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<Order>>;
  /**
   * Delete purchase order by ID
   *
   * @param {string} orderId ID of the order that needs to be deleted
   *
   * @throws {RequiredError}
   */
  deleteOrderRaw: (requestParameters: ApiDeleteOrderRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<VoidApiResponse>;
  /**
   * Delete purchase order by ID
   *
   * @param {string} orderId ID of the order that needs to be deleted
   *
   * @throws {RequiredError}
   */
  deleteOrder: (requestParameters: ApiDeleteOrderRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<void>;
  /** Returns pet inventories by status */
  getInventory: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<string>;
  /**
   * Find purchase order by ID
   *
   * @param {string} orderId ID of order that needs to be fetched
   *
   * @throws {RequiredError}
   */
  getOrderById: (requestParameters: ApiGetOrderByIdRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<Order>;
  /**
   * Place an order for a pet
   *
   * @param {Order} body
   *
   * @throws {RequiredError}
   */
  placeOrder: (requestParameters: ApiPlaceOrderRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<Order>;
}

export class StoreApi extends BaseAPI implements StoreApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /** Returns pet inventories by status */
  async getInventoryRaw(initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<string>> {
    // Build path with path parameters
    let urlPath = `/store/inventory`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /** Returns pet inventories by status */
  async getInventory(initOverrides?: InitOverrideFunction | RequestInit): Promise<string> {
    const response = await this.getInventoryRaw(initOverrides);
    return await response.value();
  }

  /**
   * Place an order for a pet
   *
   * @param {Order} body
   *
   * @throws {RequiredError}
   */
  async placeOrderRaw(requestParameters: ApiPlaceOrderRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Order>> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling placeOrderRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/store/order`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = requestParameters['body'];
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
  }

  /**
   * Place an order for a pet
   *
   * @param {Order} body
   *
   * @throws {RequiredError}
   */
  async placeOrder(requestParameters: ApiPlaceOrderRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<Order> {
    const response = await this.placeOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Find purchase order by ID
   *
   * @param {string} orderId ID of order that needs to be fetched
   *
   * @throws {RequiredError}
   */
  async getOrderByIdRaw(requestParameters: ApiGetOrderByIdRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<Order>> {
    if (requestParameters['orderId'] == null) {
      throw new RequiredError(
        'orderId',
        'Required parameter "orderId" was null or undefined when calling getOrderByIdRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/store/order/{orderId}`;
    urlPath = urlPath.replace(`{${ 'orderId' }}`, encodeURIComponent(String(requestParameters['orderId'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
  }

  /**
   * Find purchase order by ID
   *
   * @param {string} orderId ID of order that needs to be fetched
   *
   * @throws {RequiredError}
   */
  async getOrderById(requestParameters: ApiGetOrderByIdRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<Order> {
    const response = await this.getOrderByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete purchase order by ID
   *
   * @param {string} orderId ID of the order that needs to be deleted
   *
   * @throws {RequiredError}
   */
  async deleteOrderRaw(requestParameters: ApiDeleteOrderRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<VoidApiResponse> {
    if (requestParameters['orderId'] == null) {
      throw new RequiredError(
        'orderId',
        'Required parameter "orderId" was null or undefined when calling deleteOrderRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/store/order/{orderId}`;
    urlPath = urlPath.replace(`{${ 'orderId' }}`, encodeURIComponent(String(requestParameters['orderId'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new VoidApiResponse(response);
  }

  /**
   * Delete purchase order by ID
   *
   * @param {string} orderId ID of the order that needs to be deleted
   *
   * @throws {RequiredError}
   */
  async deleteOrder(requestParameters: ApiDeleteOrderRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<void> {
    const response = await this.deleteOrderRaw(requestParameters, initOverrides);
    return await response.value();
  }
}