/* tslint:disable */
/* eslint-disable */
/**
 * Petstore API
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, VoidApiResponse } from '../runtime/runtime';
import { type User, UserFromJSON, UserToJSON } from '../models/User';

export interface ApiCreateUserRequest {
    body: User;
}

export interface ApiCreateUsersWithListInputRequest {
    body: Array<User>;
}

export interface ApiDeleteUserRequest {
    username: string;
}

export interface ApiGetUserByNameRequest {
    username: string;
}

export interface ApiLoginUserRequest {
    username?: string;
    password?: string;
}

export interface ApiUpdateUserRequest {
    username: string;
    body: User;
}

/** API client for user operations */

export interface UserApiInterface {
  /**
   * Create user
   *
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  createUserRaw: (requestParameters: ApiCreateUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<User>>;
  /**
   * Creates list of users with given input array
   *
   * @param {Array<User>} body
   *
   * @throws {RequiredError}
   */
  createUsersWithListInputRaw: (requestParameters: ApiCreateUsersWithListInputRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<User>>;
  /**
   * Logs user into the system
   *
   * @param {string} username The user name for login
   * @param {string} password The password for login in clear text
   */
  loginUserRaw: (requestParameters: ApiLoginUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<any>>;
  /** Logs out current logged in user session */
  logoutUserRaw: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<any>>;
  /**
   * Get user by user name
   *
   * @param {string} username The name that needs to be fetched. Use user1 for testing
   *
   * @throws {RequiredError}
   */
  getUserByNameRaw: (requestParameters: ApiGetUserByNameRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<User>>;
  /**
   * Update user
   *
   * @param {string} username name that need to be deleted
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  updateUserRaw: (requestParameters: ApiUpdateUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<any>>;
  /**
   * Delete user
   *
   * @param {string} username The name that needs to be deleted
   *
   * @throws {RequiredError}
   */
  deleteUserRaw: (requestParameters: ApiDeleteUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<VoidApiResponse>;
  /**
   * Create user
   *
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  createUser: (requestParameters: ApiCreateUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<User>;
  /**
   * Creates list of users with given input array
   *
   * @param {Array<User>} body
   *
   * @throws {RequiredError}
   */
  createUsersWithListInput: (requestParameters: ApiCreateUsersWithListInputRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<User>;
  /**
   * Delete user
   *
   * @param {string} username The name that needs to be deleted
   *
   * @throws {RequiredError}
   */
  deleteUser: (requestParameters: ApiDeleteUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<void>;
  /**
   * Get user by user name
   *
   * @param {string} username The name that needs to be fetched. Use user1 for testing
   *
   * @throws {RequiredError}
   */
  getUserByName: (requestParameters: ApiGetUserByNameRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<User>;
  /**
   * Logs user into the system
   *
   * @param {string} username The user name for login
   * @param {string} password The password for login in clear text
   */
  loginUser: (requestParameters: ApiLoginUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any>;
  /** Logs out current logged in user session */
  logoutUser: (initOverrides?: InitOverrideFunction | RequestInit) => Promise<any>;
  /**
   * Update user
   *
   * @param {string} username name that need to be deleted
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  updateUser: (requestParameters: ApiUpdateUserRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<any>;
}

export class UserApi extends BaseAPI implements UserApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * Create user
   *
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  async createUserRaw(requestParameters: ApiCreateUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<User>> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling createUserRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/user`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = UserToJSON(requestParameters['body']);
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Create user
   *
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  async createUser(requestParameters: ApiCreateUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<User> {
    const response = await this.createUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Creates list of users with given input array
   *
   * @param {Array<User>} body
   *
   * @throws {RequiredError}
   */
  async createUsersWithListInputRaw(requestParameters: ApiCreateUsersWithListInputRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<User>> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling createUsersWithListInputRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/user/createWithList`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = requestParameters['body'];
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Creates list of users with given input array
   *
   * @param {Array<User>} body
   *
   * @throws {RequiredError}
   */
  async createUsersWithListInput(requestParameters: ApiCreateUsersWithListInputRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<User> {
    const response = await this.createUsersWithListInputRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Logs user into the system
   *
   * @param {string} username The user name for login
   * @param {string} password The password for login in clear text
   */
  async loginUserRaw(requestParameters: ApiLoginUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<any>> {
    // Build path with path parameters
    let urlPath = `/user/login`;
    // Build query parameters
    const queryParameters: any = {};
    if (requestParameters['username'] !== undefined) {
      queryParameters['username'] = requestParameters['username'];
    }
    if (requestParameters['password'] !== undefined) {
      queryParameters['password'] = requestParameters['password'];
    }
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /**
   * Logs user into the system
   *
   * @param {string} username The user name for login
   * @param {string} password The password for login in clear text
   */
  async loginUser(requestParameters: ApiLoginUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any> {
    const response = await this.loginUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /** Logs out current logged in user session */
  async logoutUserRaw(initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<any>> {
    // Build path with path parameters
    let urlPath = `/user/logout`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /** Logs out current logged in user session */
  async logoutUser(initOverrides?: InitOverrideFunction | RequestInit): Promise<any> {
    const response = await this.logoutUserRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get user by user name
   *
   * @param {string} username The name that needs to be fetched. Use user1 for testing
   *
   * @throws {RequiredError}
   */
  async getUserByNameRaw(requestParameters: ApiGetUserByNameRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<User>> {
    if (requestParameters['username'] == null) {
      throw new RequiredError(
        'username',
        'Required parameter "username" was null or undefined when calling getUserByNameRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/user/{username}`;
    urlPath = urlPath.replace(`{${ 'username' }}`, encodeURIComponent(String(requestParameters['username'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   * Get user by user name
   *
   * @param {string} username The name that needs to be fetched. Use user1 for testing
   *
   * @throws {RequiredError}
   */
  async getUserByName(requestParameters: ApiGetUserByNameRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<User> {
    const response = await this.getUserByNameRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update user
   *
   * @param {string} username name that need to be deleted
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  async updateUserRaw(requestParameters: ApiUpdateUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<any>> {
    if (requestParameters['username'] == null) {
      throw new RequiredError(
        'username',
        'Required parameter "username" was null or undefined when calling updateUserRaw().'
      );
    }
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling updateUserRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/user/{username}`;
    urlPath = urlPath.replace(`{${ 'username' }}`, encodeURIComponent(String(requestParameters['username'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = UserToJSON(requestParameters['body']);
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response);
  }

  /**
   * Update user
   *
   * @param {string} username name that need to be deleted
   * @param {User} body
   *
   * @throws {RequiredError}
   */
  async updateUser(requestParameters: ApiUpdateUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<any> {
    const response = await this.updateUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Delete user
   *
   * @param {string} username The name that needs to be deleted
   *
   * @throws {RequiredError}
   */
  async deleteUserRaw(requestParameters: ApiDeleteUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<VoidApiResponse> {
    if (requestParameters['username'] == null) {
      throw new RequiredError(
        'username',
        'Required parameter "username" was null or undefined when calling deleteUserRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/user/{username}`;
    urlPath = urlPath.replace(`{${ 'username' }}`, encodeURIComponent(String(requestParameters['username'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new VoidApiResponse(response);

  }

  /**
   * Delete user
   *
   * @param {string} username The name that needs to be deleted
   *
   * @throws {RequiredError}
   */
  async deleteUser(requestParameters: ApiDeleteUserRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<void> {
    const response = await this.deleteUserRaw(requestParameters, initOverrides);
    return await response.value();
  }
}