// Code generated by openapi-nexus. DO NOT EDIT.
// Petstore API
//
// This is a sample Pet Store Server based on the OpenAPI 3.1 specification
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// Tag model
type Tag struct {
	Id optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	Name optionalnullable.OptionalNullable[string] `json:"name,omitzero"`
}

func (c Tag) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Tag) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *Tag) GetId() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Id
}

func (c *Tag) GetName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Name
}

