// Code generated by openapi-nexus. DO NOT EDIT.
// Petstore API
//
// This is a sample Pet Store Server based on the OpenAPI 3.1 specification
//
// Generated from OpenAPI doc version 1.0.0

package components

import (
	"example.com/sdk/optionalnullable"
	"example.com/sdk/internal/utils"
)

// User model
type User struct {
	Email optionalnullable.OptionalNullable[string] `json:"email,omitzero"`
	FirstName optionalnullable.OptionalNullable[string] `json:"first_name,omitzero"`
	Id optionalnullable.OptionalNullable[string] `json:"id,omitzero"`
	LastName optionalnullable.OptionalNullable[string] `json:"last_name,omitzero"`
	Password optionalnullable.OptionalNullable[string] `json:"password,omitzero"`
	Phone optionalnullable.OptionalNullable[string] `json:"phone,omitzero"`
	UserStatus optionalnullable.OptionalNullable[string] `json:"user_status,omitzero"`
	Username optionalnullable.OptionalNullable[string] `json:"username,omitzero"`
}

func (c User) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *User) UnmarshalJSON(data []byte) error {
	requiredFields := []string{
	}
	if err := utils.UnmarshalJSON(data, c, "", false, requiredFields); err != nil {
		return err
	}
	return nil
}

func (c *User) GetEmail() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Email
}

func (c *User) GetFirstName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.FirstName
}

func (c *User) GetId() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Id
}

func (c *User) GetLastName() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.LastName
}

func (c *User) GetPassword() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Password
}

func (c *User) GetPhone() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Phone
}

func (c *User) GetUserStatus() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.UserStatus
}

func (c *User) GetUsername() optionalnullable.OptionalNullable[string] {
	if c == nil {
		var zero optionalnullable.OptionalNullable[string]
		return zero
	}
	return c.Username
}

