/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Interfaces Test
 *
 * Test fixture for oneOf/anyOf union types with interface members
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface Bar {
  bucket: string,
  endpoint: string,
  type: "bar",
}

export function instanceOfBar(value: unknown): value is Bar {
  if (!value || typeof value !== "object") {
    return false;
  }
  return "bucket" in value && (value as any)["bucket"] !== undefined && "endpoint" in value && (value as any)["endpoint"] !== undefined && "type" in value && (value as any)["type"] !== undefined;
}

export function BarFromJSON(json: any): Bar {
  return BarFromJSONTyped(json, false);
}

export function BarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bar {
  if (json == null) {
    return json;
  }
  return {
    'bucket': json['bucket'],
    'endpoint': json['endpoint'],
    'type': json['type'],
  };
}

export function BarToJSON(value?: Bar | null): any {
  return BarToJSONTyped(value, false);
}

export function BarToJSONTyped(value?: Bar | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'bucket': value['bucket'],
    'endpoint': value['endpoint'],
    'type': value['type'],
  };
}

export const BarPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};