/* tslint:disable */
/* eslint-disable */
/**
 * Union Type with Mixed Members Test
 *
 * Test fixture for union types with both interfaces and primitives
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type Bar, BarFromJSON, BarFromJSONTyped, BarToJSON, instanceOfBar } from './Bar';

export type Foo = string | number | Bar

export function FooFromJSON(json: any): Foo {
  return FooFromJSONTyped(json, false);
}

export function FooFromJSONTyped(json: any, ignoreDiscriminator: boolean): Foo {
  if (json == null) {
    return json;
  }
  if (typeof json === 'string') {
    return json;
  }
  if (typeof json === 'number') {
    return json;
  }
  if (typeof json !== 'object') {
    return json;
  }
  if (instanceOfBar(json)) {
    return BarFromJSONTyped(json, true);
  }
  return {} as any;
}

export function FooToJSON(value?: Foo | null): any {
  return FooToJSONTyped(value, false);
}

export function FooToJSONTyped(value?: Foo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'number') {
    return value;
  }
  if (typeof value !== 'object') {
    return value;
  }
  if (instanceOfBar(value)) {
    return BarToJSON(value as Bar);
  }
  return {};
}