//! Hardcoded TypeScript-fetch runtime, README, and index files.
//!
//! Replaces the minijinja templates that previously rendered these: the
//! runtime body is fully static except for the base URL, the README is a
//! handful of string substitutions, and the `index.ts` aggregators are a
//! header plus export list. No engine needed.

use heck::ToKebabCase as _;

use openapi_nexus_core::traits::file_writer::FileInfo;
use openapi_nexus_ir::types::{IrInfo, IrSpec};

const RUNTIME_TS_BODY: &str = include_str!("project_files/runtime.ts.txt");
const README_MD_BODY: &str = include_str!("project_files/README.md.txt");

/// Render the `/* tslint:disable */ ... /** ... */` header used by
/// runtime and project-index files. Terminates with a trailing newline so
/// callers can concatenate body content directly.
pub fn render_tslint_header(info: &IrInfo) -> String {
    let mut out = String::new();
    out.push_str("/* tslint:disable */\n");
    out.push_str("/* eslint-disable */\n");
    out.push_str("/**\n");
    if !info.title.is_empty() {
        out.push_str(&format!(" * {}\n", info.title));
    }
    if let Some(desc) = info.description.as_deref()
        && !desc.is_empty()
    {
        out.push_str(" *\n");
        for line in desc.split('\n') {
            out.push_str(&format!(" * {}\n", line.trim()));
        }
    }
    if !info.version.is_empty() {
        out.push_str(" *\n");
        out.push_str(&format!(
            " * The version of the OpenAPI document: {}\n",
            info.version
        ));
    }
    out.push_str(" *\n");
    out.push_str(" * NOTE: This file is auto generated by openapi-nexus.\n");
    out.push_str(" * Do not edit the file manually.\n");
    out.push_str(" */\n");
    out
}

/// Render one of the re-export index files (`index.ts`, `apis/index.ts`,
/// `models/index.ts`) as header + export statements.
pub fn render_index_file(info: &IrInfo, output_path: &str, exports: &[String]) -> FileInfo {
    let mut content = render_tslint_header(info);
    for export in exports {
        content.push_str(export);
        content.push('\n');
    }
    FileInfo::project(output_path.to_string(), content)
}

/// Render `runtime/runtime.ts` — fully static except for the base URL.
pub fn render_runtime_file(info: &IrInfo, base_path: &str) -> FileInfo {
    let mut content = render_tslint_header(info);
    content.push_str(&RUNTIME_TS_BODY.replace("{{BASE_PATH}}", base_path));
    FileInfo::runtime("runtime.ts".to_string(), content)
}

/// Render the top-level `README.md`.
pub fn render_readme_file(ir: &IrSpec) -> FileInfo {
    let title = ir.info.title.as_str();
    let version = ir.info.version.as_str();
    let description = ir
        .info
        .description
        .as_deref()
        .unwrap_or("Generated API client");
    let package_name = title.to_kebab_case();

    let content = README_MD_BODY
        .replace("{{PACKAGE_NAME}}", &package_name)
        .replace("{{DESCRIPTION}}", description)
        .replace("{{VERSION}}", version)
        .replace("{{TITLE}}", title)
        .replace("{{EXAMPLE_API_CLASS}}", "DefaultApi");

    FileInfo::readme("README.md".to_string(), content)
}
