/* tslint:disable */
/* eslint-disable */
/**
 * Test API with DELETE Response Schema
 *
 * Test fixture for DELETE operations with JSON response schemas and type alias request bodies
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { BaseAPI, type Configuration, DefaultConfig, type InitOverrideFunction, JSONApiResponse, RequiredError, ResponseError, VoidApiResponse } from '../runtime/runtime';
import type { CreateTestResourceRequest } from '../models/CreateTestResourceRequest';
import { type CreateTestResourceResponse, CreateTestResourceResponseFromJSON } from '../models/CreateTestResourceResponse';
import { type DeleteTestResourceResponse, DeleteTestResourceResponseFromJSON } from '../models/DeleteTestResourceResponse';

export interface ApiCreateTestResourceRequest {
    body: CreateTestResourceRequest;
}

export interface ApiDeleteTestResourceRequest {
    resourceId: string;
}

/** API client for test-resource operations */

export interface TestResourceApiInterface {
  /**
   * @param {CreateTestResourceRequest} body
   *
   * @throws {RequiredError}
   */
  createTestResourceRaw: (requestParameters: ApiCreateTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<CreateTestResourceResponse>>;
  /**
   * @param {string} resourceId
   *
   * @throws {RequiredError}
   */
  deleteTestResourceRaw: (requestParameters: ApiDeleteTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<JSONApiResponse<DeleteTestResourceResponse>>;
  /**
   * @param {CreateTestResourceRequest} body
   *
   * @throws {RequiredError}
   */
  createTestResource: (requestParameters: ApiCreateTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<CreateTestResourceResponse>;
  /**
   * @param {string} resourceId
   *
   * @throws {RequiredError}
   */
  deleteTestResource: (requestParameters: ApiDeleteTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit) => Promise<DeleteTestResourceResponse>;
}

export class TestResourceApi extends BaseAPI implements TestResourceApiInterface {
  /** Initialize the API client */
  constructor(configuration?: Configuration) {
    // Call BaseAPI constructor with provided configuration or default
    super(configuration ?? DefaultConfig);
  }

  /**
   * @param {CreateTestResourceRequest} body
   *
   * @throws {RequiredError}
   */
  async createTestResourceRaw(requestParameters: ApiCreateTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<CreateTestResourceResponse>> {
    if (requestParameters['body'] == null) {
      throw new RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling createTestResourceRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/v1/api/test-resource`;
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      'Content-Type': 'application/json',
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = requestParameters['body'];
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => CreateTestResourceResponseFromJSON(jsonValue));
  }

  /**
   * @param {CreateTestResourceRequest} body
   *
   * @throws {RequiredError}
   */
  async createTestResource(requestParameters: ApiCreateTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<CreateTestResourceResponse> {
    const response = await this.createTestResourceRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * @param {string} resourceId
   *
   * @throws {RequiredError}
   */
  async deleteTestResourceRaw(requestParameters: ApiDeleteTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<JSONApiResponse<DeleteTestResourceResponse>> {
    if (requestParameters['resourceId'] == null) {
      throw new RequiredError(
        'resourceId',
        'Required parameter "resourceId" was null or undefined when calling deleteTestResourceRaw().'
      );
    }
    // Build path with path parameters
    let urlPath = `/v1/api/test-resource/{resource_id}`;
    urlPath = urlPath.replace(`{${ 'resource_id' }}`, encodeURIComponent(String(requestParameters['resourceId'])));
    // Build query parameters
    const queryParameters: any = {};
    // Build headers
    const headerParameters: Record<string, string> = {
      ...this.configuration?.headers,
    };

    // Add header parameters
    // Prepare request body
    const requestBody = undefined;
    // Make request
    const response = await this.request({
        path: urlPath,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
        body: requestBody,
    }, initOverrides);
    return new JSONApiResponse(response, (jsonValue) => DeleteTestResourceResponseFromJSON(jsonValue));

  }

  /**
   * @param {string} resourceId
   *
   * @throws {RequiredError}
   */
  async deleteTestResource(requestParameters: ApiDeleteTestResourceRequest, initOverrides?: InitOverrideFunction | RequestInit): Promise<DeleteTestResourceResponse> {
    const response = await this.deleteTestResourceRaw(requestParameters, initOverrides);
    return await response.value();
  }
}