/* tslint:disable */
/* eslint-disable */
/**
 * Optional Array of Referenced Types Test
 *
 * Test case for optional array of referenced model types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
export * from './OptionalUserList';
export * from './User';
