/* tslint:disable */
/* eslint-disable */
/**
 * Intersection Type (allOf) Test
 *
 * Test fixture for allOf intersection types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */

export interface Baz {
  createdAt?: string,
  email: string,
}

export function instanceOfBaz(value: unknown): value is Baz {
  if (!value || typeof value !== "object") {
    return false;
  }
  const hasAllOriginalNames =
    "email" in value && (value as any)["email"] !== undefined;
  const hasAllTsNames =
    "email" in value && (value as any)["email"] !== undefined;
  return hasAllOriginalNames || hasAllTsNames;
}

export function BazFromJSON(json: any): Baz {
  return BazFromJSONTyped(json, false);
}

export function BazFromJSONTyped(json: any, ignoreDiscriminator: boolean): Baz {
  if (json == null) {
    return json;
  }
  return {
    'createdAt': json['createdAt'] ?? undefined,
    'email': json['email'],
  };
}

export function BazToJSON(value?: Baz | null): any {
  return BazToJSONTyped(value, false);
}

export function BazToJSONTyped(value?: Baz | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return {
    'createdAt': value['createdAt'],
    'email': value['email'],
  };
}

export const BazPropertyValidationAttributesMap: {
  [property: string]: {
    maxLength?: number,
    minLength?: number,
    pattern?: string,
    maximum?: number,
    exclusiveMaximum?: boolean,
    minimum?: number,
    exclusiveMinimum?: boolean,
    multipleOf?: number,
    maxItems?: number,
    minItems?: number,
    uniqueItems?: boolean
  }
} = {
};