/* tslint:disable */
/* eslint-disable */
/**
 * Intersection Type (allOf) Test
 *
 * Test fixture for allOf intersection types
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This file is auto generated by openapi-nexus.
 * Do not edit the file manually.
 */
import { type Bar, BarFromJSON, BarFromJSONTyped, BarToJSON, instanceOfBar } from './Bar';
import { type Baz, BazFromJSON, BazFromJSONTyped, BazToJSON, instanceOfBaz } from './Baz';

export type Foo = Bar & Baz

export function FooFromJSON(json: any): Foo {
  return FooFromJSONTyped(json, false);
}

export function FooFromJSONTyped(json: any, ignoreDiscriminator: boolean): Foo {
  if (json == null) {
    return json;
  }
  return json;
}

export function FooToJSON(value?: Foo | null): any {
  return FooToJSONTyped(value, false);
}

export function FooToJSONTyped(value?: Foo | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }
  return value;
}